<?php
/**
 * @file
 * Code for the DoSomething Metatag feature.
 */

/**
 * Implements hook_preprocess_html().
 */
function dosomething_metatag_preprocess_html(&$vars) {
  // Prevent search engines from using DMOZ site descriptions.
  $dmoz_meta_tag = array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(
      'name' => 'robots',
      'content' => 'NOODP'
    )
  );
  drupal_add_html_head($dmoz_meta_tag, 'dmoz_meta_tag');
  // Verifies DS Pinterest account.
  $pinterest_verify_tag = array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(
      'name' => 'p:domain_verify',
      'content' => '14e81c42e6c4ff0ca4ec7be173a4799f'
    )
  );
  drupal_add_html_head($pinterest_verify_tag, 'pinterest_verify_tag');
}

/**
 * Implements hook_node_view().
 */
function dosomething_metatag_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' || $view_mode == 'pitch') {
    dosomething_metatag_add_metatag_image($node);
  }
}

/**
 * Determines and sets metatag img_src metatag for a given $node and $view_mode.
 */
function dosomething_metatag_add_metatag_image($node) {
  // List of node types which use an Image EntityReference for image metatag.
  $metatag_image_node_types = array(
    'campaign' => 'field_image_campaign_cover',
    'fact_page' => 'field_intro_image',
  );
  // Foreach type that needs Image EntityReference for image metatag:
  foreach ($metatag_image_node_types as $type => $field) {
    // If this node matches the type:
    if ($type == $node->type) {
      // Set the metatag for its image field.
      dosomething_metatag_add_metatag_image_src($node, $field);
      break;
    }
  }
}

/**
 * Sets the img_src metatag with a given $node's Image EntityReference $field.
 */
function dosomething_metatag_add_metatag_image_src($node, $field) {
  // @todo: Initialize $image with default URL if image exists in the field.
  $image = NULL;
  // If a value for the image entityreference exists:
  if (!empty($node->{$field})) {
    $image_nid = $node->{$field}[LANGUAGE_NONE][0]['target_id'];
    if (module_exists('dosomething_image')) {
      // Get the image URL.
      $image = dosomething_image_get_themed_image_url($image_nid, 'landscape', '740x480');
    }
  }
  if ($image) {
    // Add <link href="[image]" rel="kik-icon"> into the HEAD.
    $attributes = array(
      'href' => $image, 
      'rel' => 'kik-icon',
    );
    drupal_add_html_head_link($attributes, TRUE);
    // Add the Facebook Open Graph tag into the HEAD.
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        "property" => "og:image",
        "content" => $image,
      ),
    );
    drupal_add_html_head($element, 'facebook_share_image');
    // Add the Twitter Image tag into the HEAD.
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        "property" => "twitter:image",
        "content" => $image,
      ),
    );
    drupal_add_html_head($element, 'twitter_image');
  }
}
