<?php
/**
 * @file
 * Code for the DoSomething Metatag feature.
 */

/**
 * Implements hook_node_view().
 */
function dosomething_metatag_node_view($node, $view_mode, $langcode) {
  // If viewing a full campaign node:
  if ($node->type == 'campaign' && $view_mode == 'full') {
    dosomething_metatag_set_metatag_image($node, 'field_image_campaign_cover');
  }
}

/**
 * Sets the img_src metatag with a given $node's Image EntityReference $field.
 */
function dosomething_metatag_set_metatag_image($node, $field) {
  // @todo: Initialize $image with default URL if image exists in the field.
  $image = NULL;
  // If a value for the image entityreference exists:
  if (!empty($node->{$field})) {
    $image_nid = $node->{$field}[LANGUAGE_NONE][0]['target_id'];
    if (module_exists('dosomething_image')) {
      // Get the image URL.
      $image = dosomething_image_get_themed_image_url($image_nid, 'landscape', '740x480');
    }
  }
  if ($image) {
    $attributes = array(
      'href' => $image, 
      'rel' => 'image_src',
    );
    drupal_add_html_head_link($attributes, TRUE);
  }
}
