<?php
/**
 * @file
 * Provides functionality to generate dummy Facts.
 */

/**
 * Implements hook_menu().
 */
function dosomething_fact_devel_menu() {
  $items = array();
  $items['admin/config/development/generate/fact'] = array(
    'title' => 'Generate facts',
    'description' => 'Generate a given number of facts. Optionally delete current facts.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_fact_devel_generate_facts_form'),
    'access arguments' => array('administer modules'),
  );
  return $items;
}

/**
 * Form constructor for generating dummy facts.
 */
function dosomething_fact_devel_generate_facts_form() {
  $form['num'] = array(
    '#type' => 'textfield',
    '#title' => t('How many facts would you like to generate?'),
    '#default_value' => 50,
    '#size' => 10,
  );
  $form['words'] = array(
    '#type' => 'textarea',
    '#title' => t('Words to include'),
    '#description' => t('Comma separated. Each fact generated will include one of the words listed.'),
    '#default_value' => "teens, high school seniors, college seniors, senior citizens, veterans, animal shelter",
  );
  $form['kill_facts'] = array(
    '#type' => 'checkbox',
    '#title' => t('Delete all facts before generating new facts.'),
    '#default_value' => FALSE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate'),
  );
  return $form;
}

/**
 * Submit handler for dosomething_fact_devel_generate_facts_form().
 */
function dosomething_fact_devel_generate_facts_form_submit($form_id, &$form_state) {
  $values = $form_state['values'];
  $words = array();
  // Build array from given word string.
  if (!empty($values['words'])) {
    $words = explode(',', $values['words']);
  }
  dosomething_fact_devel_create_facts($values['num'], $values['kill_facts'], $words);
}

/**
 * Generate some random facts.
 *
 * @param $num
 *  Number of facts to generate.
 * @param $kill
 *  Boolean that indicates if existing facts should be removed first.
 * @param $words
 *  Array of strings to include in the facts.
 */
function dosomething_fact_devel_create_facts($num = 10, $kill = FALSE, $words = array('teenage', 'mutant', 'ninja', 'turtle')) {
  // If kill existing facts:
  if ($kill) {
    // Select all facts.
    $query = new EntityFieldQuery();
    $result = $query->entityCondition('entity_type', 'fact')->execute();
    // Destroy all facts.
    entity_delete_multiple('fact', array_keys($result['fact']));
    drupal_set_message(format_plural(count($result['fact']), '1 fact deleted', '@count facts deleted.'));
  }
  // Load devel_generate.inc for dummy word/paragraph functions.
  module_load_include('inc', 'devel_generate', 'devel_generate');
  if ($num > 0) {
    $words_count = count($words);
    for ($i=0; $i < $num; $i++) {
      $fact = entity_create('fact', array(
        'fact' => devel_create_para(2) . ' ' . $words[rand(0, $words_count-1)] . ' ' .devel_create_para(2),
        'source' => devel_create_para(1),
        'url_source' => 'http://' . devel_generate_word(mt_rand(6, 12)) . '.com',
        )
      );
      $fact->save();
    }
  }
}
