<?php
/**
 * @file
 * Code for the DoSomething Static Content feature.
 */

include_once 'dosomething_static_content.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function dosomething_static_content_preprocess_node(&$vars) {
  if ($vars['type'] == 'static_content') {
    $content = $vars['content'];
    $template_vars = array(
      'text' => array(
        'subtitle',
        'intro_title',
        'intro',
        'additional_text_title',
        'additional_text',
        'call_to_action',
      ),
      'image' => array(
        '550x330',
        '800x300',
      ),
      'link' => array(
        'cta_link'
      ),
    );

    foreach ($template_vars as $key => $labels) {
      foreach ($labels as $label) {
        $field = "field_{$label}";
          if (isset($content[$field]) || isset($vars[$field])) {
          switch ($key) {
            case 'text':
              $vars[$label] = $content[$field][0]['#markup'];
              break;
            case 'image':
              $vars[$label] = dosomething_image_get_themed_image($vars[$field][0]['entity']->nid, 'landscape', $label);
            break;
            case 'link':
              $vars[$label] = l($content[$field][0]['#element']['title'], $content[$field][0]['#element']['url'], array('attributes' => array('class' => 'btn')));
            break;
            default:
              break;
          }
        }
      }
    }

    $node = entity_metadata_wrapper('node', $vars['node']);
    if ($node->field_video->value()) {
      $vars['intro_video'] = theme('dosomething_video_embed', array('field' => $node->field_video->value()));
    }

    // Preprocess gallery variables.
    dosomething_static_content_preprocess_gallery_vars($vars);
  }
}

/**
 * Preprocesses variables for the field_gallery field collection.
 *
 * @param array $vars
 *   Variable array as passed from a hook_preprocess_node.
 *
 * @see dosomething_static_content_preprocess_node().
 */
function dosomething_static_content_preprocess_gallery_vars(&$vars) {
  $content = $vars['content'];
  $gallery_count = count($content['field_gallery']['#items']);
  $vars['galleries'] = array();
  // Loop through the galleries.
  for ($i = 0; $i < $gallery_count; $i++) {
    $collection_item = reset($content['field_gallery'][$i]['entity']['field_collection_item']);
    $collection_item = $collection_item['field_gallery_item'];

    $gallery_item_count = count($collection_item['#items']);
    $vars['galleries'][$i] = array();
    for ($a = 0; $a < $gallery_item_count; $a++) {
      $gallery_item = reset($collection_item[$a]['entity']['field_collection_item']);
      $vars['galleries'][$a]['image'] = dosomething_image_get_themed_image($gallery_item['field_gallery_image']['#items'][0]['target_id'], 'sq', 'gallery_large');

      $link_field = $gallery_item['field_image_title'][0]['#element'];
      $vars['galleries'][$a]['image_title'] = $link_field['url'] ? l(t($link_field['title']), $link_field['url'], array('target' => '_blank')) : $link_field['title'];
      $vars['galleries'][$a]['image_description'] = $gallery_item['field_image_description'][0]['#markup'];
    }
  }
}
