<?php
/**
 * @file
 * Code for the DoSomething Static Content feature.
 */

include_once 'dosomething_static_content.features.inc';

function dosomething_static_content_preprocess_node(&$vars) {
  if ($vars['type'] == 'static_content') {
    $content = $vars['content'];
    $vars['hero_image'] = dosomething_image_get_themed_image($vars['field_hero_image'][0]['entity']->nid, 'horiz', 'hero_image');
    $vars['subtitle'] = $content['field_subtitle'][0]['#markup'];
    $vars['intro_title'] = $content['field_intro_title'][0]['#markup'];
    $vars['intro'] = $content['field_intro'][0]['#markup'];
    if (isset($vars['field_intro_image'][0])) {
      $vars['intro_image'] = dosomething_image_get_themed_image($vars['field_intro_image'][0]['entity']->nid, 'horiz', 'intro_image');
    }

    $node = entity_metadata_wrapper('node', $vars['node']);
    $vars['intro_video'] = theme('dosomething_video_embed', array('field' => $node->field_video->value()));

    $vars['cta'] = $content['field_call_to_action'][0]['#markup'];
    $vars['cta_button'] = l($content['field_cta_link'][0]['#element']['title'], $content['field_cta_link'][0]['#element']['url']);

    $gallery_count = count($content['field_gallery']['#items']);
    $vars['galleries'] = array();
    // Loop through the galleries.
    for ($i=0; $i<$gallery_count;$i++) {
      $collection_item = reset($content['field_gallery'][$i]['entity']['field_collection_item']);
      $collection_item = $collection_item['field_gallery_item'];

      $gallery_item_count = count($collection_item['#items']);
      $vars['galleries'][$i] = array();
      for ($a=0; $a<$gallery_item_count;$a++) {
        $gallery_item = reset($collection_item[$a]['entity']['field_collection_item']);
        $vars['galleries'][$a]['image'] = dosomething_image_get_themed_image($gallery_item['field_gallery_image']['#items'][0]['target_id'], 'sq', 'gallery_large');
        $vars['galleries'][$a]['image_title'] = $gallery_item['field_image_title'][0]['#markup'];
        $vars['galleries'][$a]['image_description'] = $gallery_item['field_image_description'][0]['#markup'];
      }
    }

    $vars['additional_text_title'] = $content['field_additional_text_title'][0]['#markup'];
    $vars['additional_text'] = $content['field_additional_text'][0]['#markup'];
  }
}