<?php
/**
 * @file
 * Code for the DoSomething User feature.
 */

include_once 'dosomething_user.features.inc';

/**
 * Implements hook_node_access().
 */
function dosomething_user_node_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;
  // Internal content types to be viewed by staff only:
  $staff_types = array('fact', 'image');
  // If viewing an internal staff type:
  if (in_array($type, $staff_types) && $op == 'view') {
    // If staff user, able to view the Fact node.
    if (dosomething_user_is_staff($account)) {
      return NODE_ACCESS_ALLOW;
    }
    // Otherwise, no facts for you.
    return NODE_ACCESS_DENY;
  }
}

 /**
  * Confirms that a specific cell phone number is valid.  A valid phone number
  * is a number with either 10 or 11 digits (as long as the first digit is a "1").
  * Valid phone numbers do not have 3 consecutive 5's in any part, nor do they
  * use punctuation where there should be numbers.  Phone numbers also do not have
  * 9 consecutive, equal digits (e.g. 999-999-9999).
  *
  * @code
  *  dosomething_user_valid_cell('123-456-7890');
  *  # => true
  *  dosomething_user_valid_cell('123.456 7890');
  *  # => true
  *  dosomething_user_valid_cell('1 (123) 456-7890');
  *  # => true
  *  dosomething_user_valid_cell('123-555-9942');
  *  # => false
  *  dosomething_user_valid_cell('1 902 #@@ 1234');
  *  # => false
  *  dosomething_user_valid_cell('999 999 9999');
  *  # => false
  * @endcode
  *
  * @param string $number
  *   The cell phone number that should be validated.
  * @return bool
  */
function dosomething_user_valid_cell($number) {
  preg_match('#^(?:\+?1([\-\s\.]{1})?)?\(?([0-9]{3})\)?(?:[\-\s\.]{1})?([0-9]{3})(?:[\-\s\.]{1})?([0-9]{4})#', $number, $valid);
  preg_match('#([0-9]{1})\1{9,}#', preg_replace('#[^0-9]+#', '', $number), $repeat);
  return !empty($valid) && empty($repeat) && strpos($number, '555') === FALSE;
}

/*
 * Determines if a user is on the ds staff.
 */
function dosomething_user_is_staff($user = NULL) {
  if ($user == NULL) {
    global $user;
  }
  // Create an array of staff role ids.
  $staff_roles = array(
    user_role_load_by_name('administrator')->rid,
    user_role_load_by_name('editor')->rid,
  );

  // Does this user have a staff rid?
  if (array_intersect(array_keys($user->roles), $staff_roles)) {
    return TRUE;
  }
  return FALSE;
}

