<?php

/**
 * Populates Terms Service and Privacy Policy node variables.
 */
function dosomething_user_update_7001() {
  variable_set('dosomething_user_node_terms_service', 1049);
  variable_set('dosomething_user_node_privacy_policy', 1050);
  variable_set('dosomething_user_login_form_display_password_link', TRUE);
}

/**
 * Implements hook_uninstall().
 */
function dosomething_user_uninstall() {
  // This list is alphabetical, please keep it that way!
  $vars = array(
    'dosomething_user_enable_clean_slate',
    'dosomething_user_login_form_display_password_link',
    'dosomething_user_login_form_copy',
    'dosomething_user_node_privacy_policy',
    'dosomething_user_node_terms_service',
    'dosomething_user_ups_access_license_number',
    'dosomething_user_ups_password',
    'dosomething_user_ups_test_integration',
    'dosomething_user_ups_username',
  );
  foreach ($vars as $var) {
    variable_del($var);
  }
}
