<?php
/**
 * @file
 * Code for the dosomething_image feature.
 */

include_once 'dosomething_image.features.inc';

/**
 * Returns an image src for any image field
 * @param array $field
 *  The image field to grab the image for.
 * @param string $ratio
 *  The desired image ratio (vert, horiz, sq).
 *
 * @return array
 *  Array containing all image attributes.
 */
function dosomething_image_get_image($field, $ratio, $crop = NULL) {
  $image = array();
  switch ($ratio) {
    case 'vert':
      return $field['entity']->field_image_vertical[LANGUAGE_NONE][0];
      break;
    case 'horiz':
      return $field['entity']->field_image_horizontal[LANGUAGE_NONE][0];
      break;
    case 'sq':
      return $field['entity']->field_image_square[LANGUAGE_NONE][0];
      break;
  }
  return;
}