<?php
/**
 * @file
 * Code for the dosomething_image feature.
 */

include_once 'dosomething_image.features.inc';

/**
 * Returns an image src for any image field
 * @param int $nid
 *  The image node id.
 * @param string $ratio
 *  The image field to pull from the desired image ratio (vert, horiz, sq).
 * @param string $style
 *  The image style preset/size to return the image.
 *
 * @return array
 *  Array containing all image attributes.
 */
function dosomething_image_get_themed_image($nid, $ratio, $style) {
  // Attempt to get that image from cache.
  if ($cached_img = cache_get('ds_img_' . $nid . '_' . $ratio . '_' . $style, 'cache_dosomething_image')) {
    return $cached_img->data;
  }
  // Theme the image.
  else {
    $node = node_load($nid);
    $image = array();
    switch ($ratio) {
      case 'vert':
        $path =  $node->field_image_portrait[LANGUAGE_NONE][0]['uri'];
        break;
      case 'horiz':
        $path = $node->field_image_landscape[LANGUAGE_NONE][0]['uri'];
        break;
      case 'sq':
        $path =  $node->field_image_square[LANGUAGE_NONE][0]['uri'];
        break;
    }

    $img = theme('image_style', array('style_name' => $style, 'path' => $path));
    // Store the themed image.
    cache_set('ds_img_' . $nid . '_' . $ratio . '_' . $style, $img, 'cache_dosomething_image');
    return $img;
  }
}
