<?php
/**
 * @file
 * Installation and schema hooks for dosomething_northstar.module.
 */

/**
 * Implements hook_schema().
 */
function dosomething_northstar_user_info_schema() {
  $schema['cache_northstar_user_info'] = drupal_get_schema_unprocessed('dosomething_northstar', 'cache_northstar_user_info');
  return $schema;
}

/**
 * Caches northstar user data.
 */
// function dosomething_northstar_user_info_update_7001(&$sandbox) {
// }


