#!/bin/sh

if [[ $1 == "--help" ]] || [[ $1 == "" ]]
  then
    read -d '' help <<"USAGE"
usage: ds [build [--install]|dbup|dbdump] [--help]

Runs helper scripts for DoSomething environment.

ds build [--install]
  Builds your environment with "drush make".  Also symlinks appropriate
  files into their respective directories.

  --install
    Runs "drush site-install" to actually install the Drupal instance.

ds --help
  Displays this help message.

USAGE
   echo "$help"
fi

if [[ $1 == "build" ]]
  then
    DRUSH_OPTS='--prepare-install --no-gitinfofile --no-cache'
    MAKEFILE='build-dosomething.make'
    TARGET='html'

    CALLPATH="/vagrant"
    ABS_CALLPATH=`cd "$CALLPATH"; pwd -P`
    BASE_PATH=`cd ..; pwd`

    echo '     _____          ___     ';
    echo '    /  /::\        /  /\    ';
    echo '   /  /:/\:\      /  /:/_   ';
    echo '  /  /:/  \:\    /  /:/ /\  ';
    echo ' /__/:/ \__\:|  /  /:/ /::\ ';
    echo ' \  \:\ /  /:/ /__/:/ /:/\:\';
    echo '  \  \:\  /:/  \  \:\/:/~/:/';
    echo '   \  \:\/:/    \  \::/ /:/ ';
    echo '    \  \::/      \__\/ /:/  ';
    echo '     \__\/         /__/:/   ';
    echo '                   \__\/    ';

    set -e
        cd $ABS_CALLPATH

    echo 'Wiping build directory...'
    rm -rf "$CALLPATH/$TARGET"

    # Create the db, if for some reason it's not there yet.
    mysql -uroot -e "CREATE DATABASE IF NOT EXISTS dosomething;"

    # Do the build
    echo 'Running drush make...'
    drush make $DRUSH_OPTS "$ABS_CALLPATH/$MAKEFILE" "$TARGET"
    set +e

    echo 'Linking modules'
    rm -rf "$ABS_CALLPATH/$TARGET/profiles/dosomething/modules/dosomething"
    ln -s "$ABS_CALLPATH/modules/dosomething" "$ABS_CALLPATH/$TARGET/profiles/dosomething/modules/dosomething"

    echo 'Linking themes'
    rm -rf "$ABS_CALLPATH/$TARGET/profiles/dosomething/themes/dosomething"
    ln -s "$ABS_CALLPATH/themes/dosomething" "$ABS_CALLPATH/$TARGET/profiles/dosomething/themes/dosomething"

    # Clear caches and Run updates
    cd "$TARGET"

    if [[ $2 == "--install" ]]
      then
        echo 'Installing site...'
        drush site-install dosomething -y --db-url=mysql://root@localhost/dosomething --site-name=DoSomething

        echo 'Granting basic permissions...'
        drush rap 'anonymous user' 'access content'
        drush rap 'authenticated user' 'access content'
    fi

    echo 'Replacing settings.php file...'
    rm -f $CALLPATH/$TARGET/sites/default/settings.php && ln -s $CALLPATH/settings.php $CALLPATH/$TARGET/sites/default/settings.php

    echo 'Updating database...'
    drush updb -y

    echo 'Clearing caches...'
    drush cc all

    echo 'Build complete.'
fi
