<?php
/**
 * @file
 * Code for the dosomething_home feature.
 */

include_once 'dosomething_home.features.inc';

/**
 * Implements hook_menu().
 */
function dosomething_home_menu() {
  $items['admin/config/dosomething/dosomething_home'] = array(
    'title' => 'DoSomething Home',
    'description' => 'DoSomething Home settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_home_admin_config_form'),
    'access arguments' => array('administer modules'),
    'file' => 'dosomething_home.admin.inc',
  );
  return $items;
}


/**
 * Implements hook_preprocess_node();
 */
function dosomething_home_preprocess_node(&$vars) {
  if ($vars['type'] != 'home') { return; }

  // Check if the Home Title variable has been set.
  if ($title = variable_get('dosomething_home_title')) {
    $vars['title'] = $title;
  }

  $vars['subtitle'] = $vars['field_subtitle'][0]['safe_value'];
  // Store this node as the signup source.
  $source = '?source=node/' . $vars['nid'];

  $campaigns = $vars['field_campaigns'];

  if (empty($campaigns)) {
    // Fallback to old stuff.
    $campaigns = array(362, 832, 8, 843, 345, 31, 15, 17, 850);  
  }

  foreach ($campaigns as $key => $campaign) {
    // Get the campaign nid.
    if (isset($campaign['target_id'])) {
      $nid = $campaign['target_id'];
    }
    else {
      $nid = $campaign;
    }
    $node = node_load($nid);

    // Grab all tiles attributes.
    $tiles = array();
    $tiles['nid'] = $nid;
    $tiles['staff_pick'] = $node->field_staff_pick[LANGUAGE_NONE][0]['value'];
    $tiles['title'] = $node->title;
    $tiles['cta'] = $node->field_call_to_action[LANGUAGE_NONE][0]['safe_value'];

    // Get the campaign cover image.
    $image_nid = $node->field_image_campaign_cover[LANGUAGE_NONE][0]['target_id'];
    if ($key == 0) {
      $tiles['modifier_classes'] = "big";
      $tiles['image'] = dosomething_image_get_themed_image_url($image_nid, 'square', '720x720');
    }
    else {
      $tiles['image'] = dosomething_image_get_themed_image_url($image_nid, 'square', '400x400');
    }


    $tiles['path'] = 'node/' . $nid;
    $tiles['pretty_path'] = drupal_get_path_alias($tiles['path']) . $source;

    $thumbnails[$nid] = theme('thumbnail', $tiles);
  }

  $vars['thumbnails'] = $thumbnails;
}
