<?php
/**
 * @file
 * Code for the dosomething_api feature.
 */

include_once 'dosomething_api.features.inc';

/**
 * Implements hook_services_request_postprocess_alter().
 */
function dosomething_api_services_request_postprocess_alter($controller, $args, &$result) {
  // If we are retrieving a node:
  if ($controller['callback'] == '_node_resource_retrieve') {
    // if it's a campaign node:
    if (isset($result->nid) && $result->type == 'campaign') {
      if (function_exists('dosomething_campaign_load')) {
        // Return the Campaign class.
        $result = dosomething_campaign_load($result, TRUE);
      }
    }
    else {
      // No content for you.
      $result = FALSE;
    }
  }
}


/**
 * Implementation of hook_services_resources().
 */
function dosomething_api_services_resources() {
  $resources = array();
  $resources['campaigns'] = array(
    'operations' => array(
      'index' => array(
        'help' => 'List all active campaigns.',
        'file' => array('type' => 'inc', 'module' => 'dosomething_api', 'name' => 'resources/campaign_resource'),
        'callback' => '_campaign_resource_index',
        'access callback' => '_campaign_resource_access',
        'args' => array(
          array(
            'name' => 'parameters',
            'optional' => TRUE,
            'type' => 'array',
            'description' => 'Parameters',
            'default value' => array(),
            'source' => array('param' => 'parameters'),
          ),
        ),
      ),
    ),
  );
  return $resources;
}
