<?php
/**
 * @file
 * Code for the dosomething_api feature.
 */

include_once 'dosomething_api.features.inc';

/**
 * Implements hook_services_request_postprocess_alter().
 */
function dosomething_api_services_request_postprocess_alter($controller, $args, &$result) {
  // If we are retrieving a node:
  if ($controller['callback'] == '_node_resource_retrieve') {
    // if it's a campaign node:
    if (isset($result->nid) && $result->type == 'campaign') {
      if (function_exists('dosomething_campaign_load')) {
        // Return the Campaign class.
        $result = dosomething_campaign_load($result, TRUE);
      }
    }
    else {
      // No content for you.
      $result = FALSE;
    }
  }
}


/**
 * Implementation of hook_services_resources().
 */
function dosomething_api_services_resources() {
  $resources = array();
  $resources['campaigns'] = array(
    'operations' => array(
      'index' => array(
        'help' => 'List all active campaigns.',
        'file' => array('type' => 'inc', 'module' => 'dosomething_api', 'name' => 'resources/campaign_resource'),
        'callback' => '_campaign_resource_index',
        'access callback' => '_campaign_resource_access',
        'args' => array(
          array(
            'name' => 'parameters',
            'optional' => TRUE,
            'type' => 'array',
            'description' => 'Parameters',
            'default value' => array(),
            'source' => array('param' => 'parameters'),
          ),
        ),
      ),
    ),
    'targeted_actions' => array(
      'signup' => array(
        'help' => 'Signup a user for a campaign. POST to campaigns/123/signup',
        'file' => array('type' => 'inc', 'module' => 'dosomething_api', 'name' => 'resources/campaign_resource'),
        'callback' => '_campaign_resource_signup',
        'access callback' => '_campaign_resource_access',
        'access arguments' => array('signup'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The nid of the Campaign node to signup for.',
          ),
          // @todo: We'll want this for SMS campaigns where uid doesn't exist?
          // array(
          //   'name' => 'uid',
          //   'optional' => TRUE,
          //   'source' => array('data' => 'uid'),
          //   'description' => 'The User uid to signup',
          //   'type' => 'int',
          // ),
        ),
      ),
      'reportback' => array(
        'help' => 'Post a user reportback for a campaign: campaigns/123/reportback',
        'file' => array('type' => 'inc', 'module' => 'dosomething_api', 'name' => 'resources/campaign_resource'),
        'callback' => '_campaign_resource_reportback',
        'access callback' => '_campaign_resource_access',
        'args' => array(
          array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The nid of the Campaign node to post a reportback.',
          ),
          array(
            'name' => 'values',
            'optional' => FALSE,
            'source' => 'data',
            'description' => 'The Reportback data',
            'type' => 'array',
          ),
        ),
      ),
    ),
  );
  return $resources;
}
