<?php
/**
 * @file
 * dosomething_campaign.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function dosomething_campaign_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'campaign-campaign-field_action_type'
  $field_instances['campaign-campaign-field_action_type'] = array(
    'bundle' => 'campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'campaign',
    'field_name' => 'field_action_type',
    'label' => 'Action Type',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'campaign-campaign-field_cause'
  $field_instances['campaign-campaign-field_cause'] = array(
    'bundle' => 'campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'campaign',
    'field_name' => 'field_cause',
    'label' => 'Cause',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Action Type');
  t('Cause');

  return $field_instances;
}
