<?php
/**
 * @file
 * Provides Do Something-specific SMS functionality.
 */
define('DOSOMETHING_SMS_WORKFLOW_ADMIN_PATH', 'admin/config/dosomething/dosomething_sms');

/**
 * Implements hook_menu().
 */
function dosomething_sms_menu() {
  $items = array();

  $items['dosomething_sms/%'] = array(
    'title' => 'SMS Receiver for Mobile Commons mData Requests',
    'page callback' => 'dosomething_sms_incoming_callback',
    'access callback' => 'dosomething_sms_incoming_check',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
  );
  $admin_path = DOSOMETHING_SMS_WORKFLOW_ADMIN_PATH;
  $items[$admin_path] = array(
    'title' => 'SMS Workflows',
    'description' => 'Overview of all SMS Workflows',
    'page callback' => 'dosomething_sms_workflow_overview_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer dosomething_sms'),
    'file' => 'dosomething_sms.admin.inc',
  );
  $items[$admin_path . '/add'] = array(
    'title' => 'Add SMS Workflow',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_sms_workflow_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer dosomething_sms'),
    'file' => 'dosomething_sms.admin.inc',
  );
  $items[$admin_path . '/%sms_workflow/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_sms_workflow_form', 4),
    'access callback' => 'user_access',
    'access arguments' => array('administer dosomething_sms'),
    'type' => MENU_CALLBACK,
    'weight' => 20,
    'file' => 'dosomething_sms.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function dosomething_sms_permission() {
  return array(
    'administer dosomething_sms' => array(
      'title' => t('Administer dosomething_sms module'),
      'description' => t('Administer access to everything in module'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_entity_info().
 */
function dosomething_sms_entity_info() {
  $info = array();
  $info['sms_workflow'] = array(
    'label' => t('SMS Workflow'),
    'base table' => 'dosomething_sms_workflow',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'title',
    ),
    'entity class' => 'SMSWorkflowEntity',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'SMSWorkflowEntityController',
    'module' => 'dosomething_sms',
  );
  return $info;
}

/**
 * Menu autoloader for /%sms_workflow.
 */
function sms_workflow_load($id) {
  $entity = entity_load('sms_workflow', array($id));
  return array_pop($entity);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function dosomething_sms_ctools_plugin_api($owner, $api) {
  if ($owner == 'conductor') {
    return array('version' => 1.0);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function dosomething_sms_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'conductor') {
    return "plugins/$plugin_type";
  }
}

/**
 * Implements hook_conductor_sms_keywords().
 *
 * Specifies conductor workflows that should trigger for a given endpoint
 *   [endpoint] => [conductor workflow]
 */
function dosomething_sms_conductor_sms_keywords() {
  $keywords = array();

  // Find files in this directory tree with the .keywords.inc extension and
  // include them to populate the keywords array.
  $files = array();
  _dosomething_sms_list_files_by_extension(dirname(__FILE__), '.keywords.inc', $files);

  foreach ($files as $file) {
    include $file;
  }

  return $keywords;
}

/**
 * Implements hook_default_conductor_workflows().
 * Searches for local .workflows.inc files for instantiated ConductorWorkflows to add to array.
 */
function dosomething_sms_default_conductor_workflows() {
  $workflows = array();

  // Find files in this directory tree with the .workflows.inc extension and
  // include them to populate the workflows array.
  $files = array();
  _dosomething_sms_list_files_by_extension(dirname(__FILE__), '.workflows.inc', $files);

  foreach ($files as $file) {
    include $file;
  }

  return $workflows;
}

/**
 * Helper function to find all files within a directory that end with the given extension.
 *
 * @param string $dir
 *   Directory to search for files.
 * @param string $file_ext
 *   File extension of files to search for.
 * @param array $matching_files
 *   The files that match the $file_ext being searched for.
 */
function _dosomething_sms_list_files_by_extension($dir, $file_ext, &$matching_files) {
  $files = scandir($dir);
  foreach ($files as $file) {
    if ($file != '.' && $file != '..') {
      $path = $dir . '/' . $file;

      if (is_dir($path)) {
        _dosomething_sms_list_files_by_extension($path, $file_ext, $matching_files);
      }
      elseif (preg_match('/'  . $file_ext . '$/', $path) === 1) {
        $matching_files[] = $path;
      }
    }
  }
}

/**
 * Callback for Mobile Commons mData requests. Allows for different endpoints
 * to trigger different keyword paths.
 *
 * @param string $path
 *   Keyword associated with a ConductorWorkflow that the request will be handled by.
 */
function dosomething_sms_incoming_callback($path) {
  // Direct correlation between path endpoint and keyword used. If the path doesn't
  // match any keyword specified in the array of keywords, then error out.
  $keyword = $path;
  $keyword_map = module_invoke_all('conductor_sms_keywords');
  if (!array_key_exists($path, $keyword_map)) {
    watchdog('dosomething_sms', "Received message at unsupported path: /dosomething_sms/$path");
    return NULL;
  }

  // Build context for the conductor workflow
  $message = isset($_REQUEST['args']) ? $_REQUEST['args'] : FALSE;
  $carrier = isset($_REQUEST['carrier']) ? $_REQUEST['carrier'] : FALSE;
  $sender = isset($_REQUEST['phone']) ? $_REQUEST['phone'] : FALSE;

  $context = array(
    'message' => $message,
    'keyword' => $keyword,
    'carrier' => $carrier,
    'sender' => $sender,
  );
  if (variable_get('dosomething_sms_workflow_log')) {
    watchdog('dosomething_sms', '$context: ' . json_encode($context));
  }

  // Pass message on to Conductor to handle and generate a response
  $output = '';
  conductor_sms_response($output, $context);

  // Reply with output back to Mobile Commons. If empty, Mobile Commons will ignore it.
  print $output;

  return NULL;
}

/**
 * Filter to ensure incoming texts are coming from Mobile Commons' IP.
 */
function dosomething_sms_incoming_check() {
  if (variable_get('dosomething_sms_workflow_access_bypass')) {
    return TRUE;
  }
  // Valid IP range as specified by Mobile Commons is: 64.22.127.0/24.
  // This translates to any IP 64.22.127.0 - 64.22.127.255
  $ips = array();
  $ips[] = ip_address();
  if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $ips[] = $_SERVER['HTTP_X_FORWARDED_FOR'];
  }
  foreach ($ips as $ip) {
    if (preg_match("/^(64.22.127.[0-9]*|67.214.213.[0-9]*)/", $ip)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Subscribe to a Mobile Commons opt-in path.
 *
 * @param string $phone
 *   Phone number of the user.
 * @param int $opt_in_path
 *   Mobile Commons opt-in path id.
 * @param array $args
 *   Additional arguments.
 */
function dosomething_sms_mobilecommons_opt_in($phone, $opt_in_path, $args = array()) {
  $content = array(
    'opt_in_path[]' => $opt_in_path,
    'person' => array(
      'phone' => $phone,
    ),
  );

  if (!empty($args)) {
    foreach ($args as $key => $val) {
      $content[$key] = urlencode($val);
    }
  }

  mobilecommons_request('opt_in', $content);
}

/**
 * Unsubscribe the user from a Mobile Commons campaign.
 *
 * @param string $phone
 *   Phone number of the user.
 * @param int $campaign
 *   A single campaign ID to opt out of.
 */
function dosomething_sms_mobilecommons_opt_out($phone, $campaign) {
  $content = array(
    'person' => array(
      'phone' => $phone,
    ),
  );

  $content['campaign'] = $campaign;

  mobilecommons_request('opt_out', $content);
}

/**
 * Returns all SMS Workflow data as an array of objects.
 */
function dosomething_sms_get_sms_workflows($filter_active = TRUE) {
  $query = db_select('dosomething_sms_workflow', 'sw')->fields('sw');
  if ($filter_active) {
    $query->condition('status', 0, '>');
  }
  return $query->execute()->fetchAll();
}
