<?php
/**
 * @file
 * Code for the DoSomething Legacy module.
 */

/**
 * Determines if a campaign is a legacy campaign.
 *
 * @param object $node
 *  A node object.
 * @return bool
 *  Returns true if node is a legacy campaign, else false.
 */
function dosomething_legacy_check($node) {
  $momm = variable_get('MOMM');
  if ($node->nid == $momm['beta']) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Handles redirects to the legacy app.
 *
 * @param int $nid
 *  Old world nid.
 */
function dosomething_legacy_goto($nid) {
  $momm = variable_get('MOMM');
  drupal_goto('https://www.dosomething.org/node/' . $momm['legacy']);
}

/*
 * Implements hook_entity_view_mode_alter().
 *
 */
function dosomething_legacy_entity_view_mode_alter(&$view_mode, $context) {
  // Is this a campaign node?
  if ($context['entity_type'] == 'node' && $context['entity']->type == 'campaign') {
    $node = $context['entity'];
    // If legacy campaign and user is signed up:
    if (dosomething_legacy_check($node) && dosomething_signup_exists($node->nid)) {
      // Redirect to legacy campaign.
      dosomething_legacy_goto($node->nid);
    }
  }
}
