<?php

/**
 * @file
 * Code for DS Canada integration.
 */

define('DOSOMETHING_CANADA_WATCHDOG', 'dosomething_canada');
define('DOSOMETHING_CANADA_USER_SOURCE', 'dosomething_canada');

// In lieu of a future, global management solution, standardize feedback
// messages here.
define('DOSOMETHING_CANADA_MSG_FAILED_LOGIN', "Sorry, we don't recognize that email and password.");


// -----------------------------------------------------------------------
// Hook implementations

/**
 * Implements hook_external_auth_method().
 */
function dosomething_canada_external_auth_method() {
  $items = array();
  $items[] = array(
    'title'                   => 'DoSomething Canada',
    'description'             => 'Authenticates using TGI API.',
    'login controller'        => 'DosomethingCanadaLoginController',
    'register controller'     => 'DosomethingCanadaRegisterController',
    'profile sync controller' => 'DosomethingCanadaProfileSyncController',
    'user pass controller'    => 'DosomethingCanadaUserPassController',
   );
  return $items;
}

// -----------------------------------------------------------------------
// SSO helpers

/**
 * Create an SSO client instance as a singleton.
 *
 * @return CanadaSSOClient
 */
function dosomething_canada_get_sso() {
  static $sso;

  if (empty($sso)) {
    $sso = new CanadaSSOClient(
      variable_get('dosomething_canada_sso_url'),
      variable_get('dosomething_canada_sso_appid'),
      variable_get('dosomething_canada_sso_key')
    );
  }
  return $sso;
}

// -----------------------------------------------------------------------
