<?php

/**
 * @file
 * Code for DS Canada integration.
 */

define('DOSOMETHING_CANADA_WATCHDOG', 'dosomething_canada');
define('DOSOMETHING_CANADA_USER_SOURCE', 'dosomething_canada');

// In lieu of a future, global management solution, standardize feedback
// messages here.
define('DOSOMETHING_CANADA_MSG_FAILED_LOGIN', "Sorry, we don't recognize that email and password.");


// -----------------------------------------------------------------------
// Hook implementations

/**
 * Implements hook_external_auth_method().
 */
function dosomething_canada_external_auth_method() {
  $items = array();
  $items[] = array(
    'title'               => 'DoSomething Canada',
    'description'         => 'Authenticates using TGI API.',
    'login controller'    => 'DosomethingCanadaLoginController',
    'register controller' => 'DosomethingCanadaRegisterController',
   );
  return $items;
}

// -----------------------------------------------------------------------
// SSO helpers

/**
 * Create an SSO client instance as a singleton.
 *
 * @return CanadaSSOClient
 */
function dosomething_canada_get_sso() {
  static $sso;

  if (empty($sso)) {
    $sso = new CanadaSSOClient(
      variable_get('dosomething_canada_sso_url'),
      variable_get('dosomething_canada_sso_appid'),
      variable_get('dosomething_canada_sso_key')
    );
  }
  return $sso;
}

/**
 * Construct a well-formed user object that the API integration library
 * can accept.
 *
 * @param $email
 * @param $pass
 * @param $account
 * @return stdClass
 */
function dosomething_canada_create_sso_user($email, $pass, $account) {
  $user = new stdClass();
  $user->email = $email;
  $user->password = $pass;

  if (!empty($account->field_birthdate['und'][0])) {
    $user->dob = date('Y-m-d', strtotime($account->field_birthdate['und'][0]['value']));
  }

  if (!empty($account->field_mobile['und'][0])) {
    $user->mobile = $account->field_mobile['und'][0]['value'];
  }

  if (!empty($account->field_first_name['und'][0])) {
    $user->firstName = $account->field_first_name['und'][0]['value'];
  }

  if (!empty($account->field_last_name['und'][0])) {
    $user->lastName = $account->field_last_name['und'][0]['value'];
  }

  return $user;
}

// -----------------------------------------------------------------------
