<?php
/**
 * @file
 * Code for the DoSomething Campaign Group feature.
 */

include_once 'dosomething_campaign_group.features.inc';


function dosomething_campaign_group_preprocess_node(&$vars) {
  if ($vars['type'] != 'campaign_group' && $vars['view_mode'] != 'full') { return; }
    $content = $vars['content'];
    $template_vars = array(
      'text' => array(
        'additional_text',
        'additional_text_title',
        'intro_title',
        'intro',
        'call_to_action',
      ),
      'image' => array(
        'additional_text_image',
        'intro_image',
      ),
    );

  // Determine Campaign Group attributes based on its children.
  $campaign_group_data = dosomething_campaign_group_get_child_data($vars['node']);

  // Store child nid's to render within the theme.
  $vars['campaigns'] = $campaign_group_data['nids'];

  // If Campaign Group is in pre-launch state:
  if ($campaign_group_data['pre_launch']) {
    // Add relevant fields to set as template vars.
    $template_vars['text'][] = 'pre_launch_copy';
    $template_vars['text'][] = 'pre_launch_title';
  }

  foreach ($template_vars as $key => $labels) {
    foreach ($labels as $label) {
      $field = "field_{$label}";
        if (isset($content[$field])) {
        switch ($key) {
          case 'text':
            $vars[$label] = $content[$field][0]['#markup'];
            break;
          case 'image':
            $size = '550x300';
            $vars[$label] = dosomething_image_get_themed_image($vars[$field][0]['entity']->nid, 'landscape', $size);
          default:
            break;
        }
      }
    }
  }

  $node = menu_get_object();
  $wrapper = entity_metadata_wrapper('node', $node);

  // Timing.
  $display_date = $wrapper->field_display_end_date->value();
  // Check if there is a value in the date field.
  $high_season = $wrapper->field_high_season->value();
  if ($display_date == 1 && isset($high_season)) {
    $end_date = date('F d', $wrapper->field_high_season->value2->value());
    $vars['end_date'] = 'Ends ' . $end_date;
  }

  // Hero Images.
  dosomething_helpers_preprocess_hero_images($vars);

  // Add inline css based on vars.
  dosomething_helpers_add_inline_css($vars);

  $wrapper = entity_metadata_wrapper('node', $vars['node']);
  if ($wrapper->field_video->value()->field_video_id) {
    $vars['intro_video'] = theme('dosomething_video_embed', array('field' => $wrapper->field_video->value()));
  }

  $scholarship = $wrapper->field_scholarship_amount->value();
  if (isset($scholarship)) {
    $vars['scholarship'] = 'Win a $' . number_format($scholarship, 0, '', ',') . ' Scholarship';
  }

  // Collect all field_collection values as vars.
  $field_collections = array('faq');
  foreach ($field_collections as $fc) {
    $vars[$fc] = dosomething_helpers_get_field_collection_values($wrapper, 'field_' . $fc);
  }

  if (!empty($vars['field_partners'])) {
    // Sets partners, sponsors, and partner_info arrays if present.
    dosomething_helpers_preprocess_partners_vars($vars);
  }

  // Preprocess gallery variables.
  dosomething_static_content_preprocess_galleries($vars);


  // Theme modal items if any exist.
  $modal_items = array();

  if (isset($vars['faq'])) {
    $modal_items['faq'] = $vars['faq'];
  }

  if (isset($vars['partner_info']) && !empty($vars['partner_info'])) {
    $modal_items['partner_info'] = $vars['partner_info'];
  }

  if (!empty($modal_items)) {
    $vars['modals'] = theme('modal_links', array('modals' => $modal_items));
  }

  // Include Zendesk Form
  $vars['zendesk_form'] = drupal_get_form('dosomething_zendesk_form', $node);


}

/**
 * For a given campaign_group $node, get child nids and determine if pre_launch.
 *
 * @param object $node
 *   Loaded campaign_group Node.
 *
 * @return array
 */
function dosomething_campaign_group_get_child_data($node) {
  // Initalize return array.
  $data = array(
    'pre_launch' => TRUE,
    'nids' => array(),
  );
  if (!empty($node->field_campaigns)) {
    $clc = dosomething_helpers_get_current_language_content_code();
    foreach ($node->field_campaigns[$clc] as $delta => $value) {
      // Add the child nid to nid's array.
      $data['nids'][] = $value['entity']->nid;
      // If the node is published:
      if ($value['entity']->status) {
        // The Campaign Group node is not in pre-launch.
        $data['pre_launch'] = FALSE;
      }
    }
  }
  return $data;
}

/**
 * Returns a Campaign Group parent nid for a given node $nid.
 *
 */
function dosomething_campaign_group_get_parent_nid($nid) {
  $result = db_select('field_data_field_campaigns', 'c')
    ->condition('field_campaigns_target_id', $nid)
    ->condition('bundle', 'campaign_group')
    ->condition('deleted', 0)
    ->fields('c', array('entity_id'))
    ->execute();
  return $result->fetchField(0);
}
