<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Returns array of values of sponser data.
 *
 * @param object $sponsor_field_wrapper
 *   An entity_metadata_wrapper object.
 *
 * @return mixed
 *   Multi-dimensional array of sponsor data or NULL if empty.
 *
 */
function dosomething_taxonomy_get_sponsors($sponsor_field_wrapper) {
  foreach ($sponsor_field_wrapper->getIterator() as $delta => $term_wrapper) {
    $sponsors[$delta]['name']  = $term_wrapper->name->value();
    if (property_exists($term_wrapper->field_image_sponsor_logo, 'nid')) {
    $sponsor_img_nid =  $term_wrapper->field_image_sponsor_logo->value()->nid;
      $sponsors[$delta]['img'] = dosomething_image_get_image($sponsor_img_nid, 'sq', '310x310');
    }
  }
  if (!is_null($sponsors)) {
    return $sponsors;
  }
  return NULL;
}