<?php
/**
 * @file
 * Code for the DoSomething Global feature.
 */

include_once 'dosomething_global.features.inc';

/**
 * Implements hook_form_alter().
 */
function dosomething_global_form_campaign_node_form_alter(&$form, &$form_state, $form_id) {
  // Get translatable fields.
  $fields = $form_state['field'];
  foreach ($fields as $field) {
    $translatable = $field[LANGUAGE_NONE]['field']['translatable']);
    if ($field[LANGUAGE_NONE]['field']['translatable']) {
      $translatable_fields[] = $field;
    }
  }
}
