<?php
/**
 * @file
 * Code for the DoSomething Global feature.
 */

include_once 'dosomething_global.features.inc';
define("TRANSLATABLE_TYPES", 'static_content,campaign,home');

// Default language: Global English
define('DOSOMETHING_GLOBAL_DEFAULT_LANG_CODE', 'en-global');

/**
 * Implements hook_init().
 */
function dosomething_global_init() {
  global $user;

  // Redirect people hitting the homepage to there local version
  if (drupal_is_front_page() && is_numeric(arg(1))) {

    // Cannot use arg() as it doesn't return path prefixes
    $path = request_path();
    $args = explode('/', $path);

    // Only apply logic to Global homepage.
    if (!empty($path) && $args[0] != 'node') {
      return;
    }

    $country_code = dosomething_settings_get_geo_country_code();
    $language = dosomething_global_convert_country_to_language($country_code);
    // No matching language, serve the global page
    if ($language == NULL) {
      return;
    }

    // Get users local path prefix and verify we support it
    $path_prefix = dosomething_global_get_prefix_for_language($language);
    if ($path_prefix == NULL) {
      return;
    }

    // Redirect user
    drupal_goto($path_prefix . '/' . current_path());
  }

  // Verify we're dealing with a node edit with no translation specification in the URL
  if (arg(0) == "node" && is_numeric(arg(1)) && arg(2) == "edit" && null == arg(3)) {
    // Load the page node and user
    $nid = arg(1);
    $node = node_load($nid);

    // Load the languages being used
    $src_language = $node->language;
    $user_language = $user->language ?: 'en';

    // If we're not working on a translation, no need to re-direct.
    if ($src_language != $user_language) {
      // Determines if the url needs the /add/source/ component
      $new_translation_prefix = isset($node->translations->data[$user_language]) ? '' : 'add/' . $src_language . '/';

      // Append the user language
      $lang_append = $new_translation_prefix . $user_language;

      // Build complete URL and redirect
      $new_url = str_replace(' ', '', '/node/' . $nid . '/edit/' . $lang_append);
      drupal_goto($new_url);
    }
  }

  // Handle translation redirects for authenticated and anonymous users when
  // they request bare (Global English) URLs.
  //
  // Passing 'noredirect=1' will defeat the redirect.
  if (arg(0) == 'node' && is_numeric(arg(1)) && empty(arg(2)) &&
      !dosomething_global_is_translation_request() &&
      empty($_GET['noredirect'])) {

    if ($user->uid) {
      dosomething_global_redirect_node_auth();
    } else {
      dosomething_global_redirect_node_anon();
    }
  }

}

/**
 * Implements hook_node_insert().
 */
function dosomething_global_node_insert($node) {
  $user = user_load($node->uid);
  // If we are saving a new campaign and the user is a regional admin.
  if ($node->type == 'campaign' && dosomething_global_is_regional_admin($user)) {
    // Set the node language to the author's lang.
    $node->language = dosomething_global_get_user_language($user);
  }
}

/**
 * Implements hook_form_alter().
 */
function dosomething_global_form_node_form_alter(&$form, &$form_state, $form_id) {
  // Only run this form alter on translatable types.
  $translatable_types = explode(',', TRANSLATABLE_TYPES);
  if (!(in_array($form['type']['#value'], $translatable_types))) {
    return;
  }
  // Get the last item in the url, to get the edit/add node language.
  $node_lang = array_pop(explode('/', (parse_url(current_path(), PHP_URL_PATH))));
  $translations = $form['#node']->translations->data;
  // If we are on a node lang page, and a translation exists
  if (array_key_exists($node_lang, $translations)) {
    // Set the publish status to the translation status
    $form['translation']['status']['#default_value'] = $translations[$node_lang]['status'];
  }
  else {
    // Otherwise, don't autocheck that publish box.
    $form['translation']['status']['#default_value'] = FALSE;
  }

  // Check if the user is a mexico or brazil admin
  if (dosomething_global_is_regional_admin()) {
    // Hide language selector if it's shown.
    if (!empty($form['language']['#access'])) {
      $form['language']['#access'] = FALSE;
    }
    // Get translatable fields.
    $fields = $form_state['field'];
    foreach ($fields as $field_name => $field) {
      $field_info = field_info_field($field_name);
      // If the field is not translatable disable access
      if (!$field_info['translatable'] && strpos($field_name, '#') === FALSE) {
        $form[$field_name]['#access'] = FALSE;
      }
    }
    // Hide some extra things from the form.
    $form['translation']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;
  }
}

/**
 * Implements hook_menu_alter().
 */
function dosomething_global_menu_alter(&$items) {
  // Hide the translate tab from regional admins
  $items['node/%node/translate']['access callback'] = 'user_access';
  $items['node/%node/translate']['access arguments'] = array('translate any entity');

  // // Make sure all admins can see this
  $items['admin/content/search']['access callback'] = 'user_access';
  $items['admin/content/search']['access arguments'] = array('access administration menu');
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function dosomething_global_menu_local_tasks_alter(&$data, $route_name) {
  // Verify we're operating on a node edit page
  if ($route_name['path'] === 'node/%/edit' || $route_name['path'] === 'node/%/edit/add/%/%') {
    // Only perform this for regional admins
    if (dosomething_global_is_regional_admin()) {
      // Remove tabs from the edit page
      if (isset($data['tabs'][1]['output'])) {
        unset($data['tabs'][1]['output']);
      }

      // Remove the translate tab in CMS side for regional admins
      $remove_translate_tab_script = "jQuery(document).ready(function () { var tabMenu = jQuery('ul.tabs.primary'); var tab = tabMenu.find('li > a:contains(\"Translate\")').parent().remove(); });";
      drupal_add_js($remove_translate_tab_script, 'inline');
    }
  }
}

/**
 * Returns if the user is a regional admin
 *
 * @param Object $user
 *   Optional - A specified user to check
 *
 * @return SelectQuery object
 */
function dosomething_global_is_regional_admin($user = NULL) {
  if (!isset($user)) {
    global $user;
  }
  $regional_roles = _dosomething_global_get_regional_roles();
  foreach ($user->roles as $role) {
    if (in_array($role, $regional_roles)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Get the roles that are defined as regional admins.
 *
 * @return - array
 *  The roles that are regional admins.
 */
function _dosomething_global_get_regional_roles() {
  $languages = variable_get('dosomething_global_language_map', '');
  foreach ($languages as $language) {
    if (isset($language['default_roles'][0])) {
      $roles[] = $language['default_roles'][0];
    }
  }
  return $roles;
}

/**
 * Returns the user's langauge based on the role.
 *
 * @param Object $user
 *   Optional - A specified user to check
 *
 * @return string
 *   The language key.
 */
function dosomething_global_get_user_language($user = NULL) {
  if (!isset($user)) {
    global $user;
  }
  $lang_map = variable_get('dosomething_global_language_map', '');
  foreach ($lang_map as $lang_key => $lang) {
    // If we have a role with the language.
    if (isset($lang['default_roles'][0])) {
      $role_to_lang[$lang_key] = $lang['default_roles'][0];
    }
  }
  foreach ($user->roles as $role) {
    // If the array search returns a lang key, return that.
    if (is_string($key = array_search($role, $role_to_lang))) {
      return $key;
    }

  }
  // If we didn't find a user role return english default.
  return 'en';
}

/**
 * Returns a list of all the countries defined in the strongarm
 *
 * @return array
 *  All of the supported countries
 */
 function dosomething_global_get_countries() {
   $lang_map = variable_get('dosomething_global_language_map', '');
   $countries = array();
   foreach ($lang_map as $lang) {
     $country = $lang['country'];

     // Prevents global english from slipping through
     if ($country != NULL) {
       array_push($countries, $country);
     }
   }
   array_push($countries, "global");
   return $countries;
 }

/**
 * Gets the country from a given language.
 *
 * @param string language
 *  A two letter language code.
 *
 * @return string language
 *  The country that maps to the language passed in.
 */
function dosomething_global_convert_language_to_country($language) {
  $lang_map = variable_get('dosomething_global_language_map', '');
  return $lang_map[$language]['country'];
}

/**
 * Converts the given country into its assigned language.
 *
 * @param string country
 *  The country Code
 *
 * @return
 *  The language mapped to this country or NULL
 */
function dosomething_global_convert_country_to_language($country) {
  $lang_map = variable_get('dosomething_global_language_map', '');
  foreach ($lang_map as $lang_key => $lang) {
    if ($lang['country'] == $country) {
      return $lang_key;
    }
  }
  // It is not the job of this function to determine a default language
  return NULL;
}

function dosomething_global_get_prefix_for_language($language) {
  $result = db_select('languages', 'l')
    ->fields('l')
    ->condition('language', $language, '=')
    ->execute()
    ->fetchAssoc();
  return $result['prefix'];
}

/**
 * Get the appropriate language for the application.
 *
 * @param $account
 *   The user's account
 * @param  $node
 *   Optional node.
 *
 */
function dosomething_global_get_language($account, stdClass $node = NULL) {
  // Respect the URL first.
  $request_path = explode('/', request_path());
  if (!empty($request_path[0])) {
    $languages = language_list();
    foreach ($languages as $langcode => $lang_data) {
      if ($lang_data->prefix == $request_path[0]) {
        return $langcode;
      }
    }
  }

  if (is_object($node)) {
    // If there is a published translation for the node in the user's language, use it.
    if ($node->translations->data{$account->language}['status']) {
      $language = $account->language;
    }
    // If there's no published translation in their language try the default language.
    elseif ($node->translations->data[language_default('language')]['status']) {
      $language = language_default('language');
    }
    // Default to node language if there's no translation in their language and no translation in the system default language.
    else {
      $language = $node->language;
    }
  }
  elseif ($language = $account->language) {
    return $language;
  }
  else {
    $language = dosomething_global_get_user_language($account);
  }

  return $language;
}

/**
 * Detect from the original request path whether the current request is for
 * translated (non-Global English) content.
 *
 * This assumes that Global English is mapped to a blank ('') URL prefix.
 *
 * @return bool
 */
function dosomething_global_is_translation_request() {

  $languages = language_list();
  $matches = array();

  if (preg_match('/([^\/]+)\//', request_path(), $matches)) {
    if (!empty($matches[1])) {
      foreach ($languages as $sys_lang) {

        // If the prefix matches a language prefix besides that of Global
        // English:
        if ($matches[1] == $sys_lang->prefix && $sys_lang->language != DOSOMETHING_GLOBAL_DEFAULT_LANG_CODE) {

          return TRUE;
        }
      }
    }
  }
  return FALSE;
}

/**
 * Handle redirects to translated content for authenticated users. In this
 * case:
 *
 * - If my profile includes a language preference,
 * - and I'm not a privileged user (admin, editor, etc.),
 * - and I request a bare URL (e.g., /campaigns/sample),
 * - and there is a translation available (e.g., /voluntario/ejemplo),
 * - then issue a 302 redirect to the translation's URL.
 */
function dosomething_global_redirect_node_auth() {
  global $user;

  // Don't do redirects for privileged users.
  if (user_access('access administration menu')) {
    return;
  }

  // User language.
  $user_lang_code = $user->language ?: 'en';

  // All languages, as an array of objects.
  $languages = language_list();

  $global_lang_code = DOSOMETHING_GLOBAL_DEFAULT_LANG_CODE;

  if (empty($languages[$global_lang_code])) {
    watchdog('dosomething_global', "Can't load %lang language",
      array('%lang' => $global_lang_code), WATCHDOG_ERROR);
    return;
  }

  // Don't redirect for Global English speakers.
  if ($user_lang_code == $global_lang_code) {
    return;
  }

  $node = node_load(arg(1));

  if ($languages[$user_lang_code]) {
    dosomething_global_redirect_node_language($node, $user_lang_code, 302);
  }
}

/**
 * Handle redirects to translated content for anonymous users. In this
 * case:
 *
 * - If I request a bare URL (e.g., /campaigns/sample),
 * - and there is a translation available (e.g., /voluntario/ejemplo),
 * - then issue a 301 redirect to the translation's URL.
 */
function dosomething_global_redirect_node_anon() {

  // All languages, as an array of objects.
  $languages = language_list();

  // Map GeoIP country to a system language. Default to 'en-global'.
  $user_country_code = dosomething_settings_get_geo_country_code();
  $target_lang_code = DOSOMETHING_GLOBAL_DEFAULT_LANG_CODE;

  $lang_map = variable_get('dosomething_global_language_map', '');
  foreach ($lang_map as $lang_key => $lang) {
    if ($lang['country'] == $user_country_code) {
      $target_lang_code = $lang_key;
      break;
    }
  }

  // If we're actually supposed to show the en-global version:
  if ($target_lang_code == DOSOMETHING_GLOBAL_DEFAULT_LANG_CODE) {
    return;
  }

  if (empty($languages[$target_lang_code])) {
    watchdog('dosomething_global', "Can't load %lang language",
      array('%lang' => $target_lang_code), WATCHDOG_ERROR);
    return;
  }

  $node = node_load(arg(1));

  dosomething_global_redirect_node_language($node, $target_lang_code, 301);
}

/**
 * Given a node object, a language code (e.g., "en", "en-global", "es-mx"),
 * and a redirect status, redirect the request to the desired translation's
 * URL.
 *
 * @param $node
 * @param $language_code
 * @param int $redirect_status
 */
function dosomething_global_redirect_node_language($node, $language_code, $redirect_status = 302) {

  $languages = language_list();

  // Can only redirect to an published, translated version.
  if (!empty($node->translations->data[$language_code]) && (bool)$node->translations->data[$language_code]['status']) {

    $target_node = $node->translations->data[$language_code];

    // Might be overly formal: We could pull 'node/nid' from the current
    // request. This is in case of the unlikely (impossible?) event that
    // a translated version of this node has a different entity ID.
    $target_path = sprintf('node/%s', $target_node['entity_id']);

    drupal_goto(url($target_path, array('language' => $languages[$language_code])), array(), $redirect_status);
  }
}

/**
 * Build a URL that appropriately adds the prefix.
 *
 * @param string $path
 *   The path to pass to url()
 * @param  $options
 *   Optional options array to be passed to url()
 *
 */
function dosomething_global_url($path, $options = NULL) {
  global $language;
  $languages = language_list();

  if (!isset($options['language'])) {
    if (isset($language)) {
      $options['language'] = $language->language;
    }
    else {
      $options['language'] = language_default('language');
    }
  }
  if (!isset($options['prefix']) && !empty($languages[$options['language']]->prefix)) {
    $options['prefix'] = $languages[$options['language']]->prefix . '/';
  }
  return url($path, $options);
}
