<?php
/**
 * @file
 * Installation for dosomething_uk.module.
 */

/**
 * Implements hook_install().
 */
function dosomething_uk_install() {
  // Setup OAuth access.
  variable_set('dosomething_uk_oauth_url',    getenv('DS_UK_OAUTH_URL'));
  variable_set('dosomething_uk_oauth_key',    getenv('DS_UK_OAUTH_KEY'));
  variable_set('dosomething_uk_oauth_secret', getenv('DS_UK_OAUTH_SECRET'));

  _dosomething_uk_install_set_display_defaults();
}

/**
 * Sets Login and Registration form variable.
 */
function dosomething_uk_update_7003() {
  _dosomething_uk_install_set_display_defaults();
}

/**
 * Implements hook_uninstall().
 */
function dosomething_uk_uninstall() {
  $vars = array(
    'dosomething_uk_oauth_url',
    'dosomething_uk_oauth_key',
    'dosomething_uk_oauth_secret',
    'dosomething_uk_oauth_callback',
    'dosomething_user_login_form_copy',
    'dosomething_user_login_form_display_password_link',
    'dosomething_user_register_form_display_last_name',
    'dosomething_user_register_form_display_opt_in_email',
    'dosomething_user_register_form_display_opt_in_sms',
    'dosomething_user_register_form_display_postal_code',
  );
  foreach ($vars as $var) {
    variable_del($var);
  }
}

/**
 * Sets Login and Registration form variable.
 */
function _dosomething_uk_install_set_display_defaults() {
  // Login Form copy.
  $copy = "(use your vInspired login if you have one)";
  variable_set('dosomething_user_login_form_copy', $copy);
  // Hide the Forgot password link.
  variable_set('dosomething_user_login_form_display_password_link', FALSE);
  // Display the Last Name field.
  variable_set('dosomething_user_register_form_display_last_name', TRUE);
  // Display the Opt-in fields.
  variable_set('dosomething_user_register_form_display_opt_in_email', TRUE);
  variable_set('dosomething_user_register_form_display_opt_in_sms', TRUE);
  // Display the Postal Code element within field_address.
  variable_set('dosomething_user_register_form_display_postal_code', TRUE);
}
