<?php

/**
 * @file
 * Functionality for users on DoSomething.
 */

 /**
  * Confirms that a specific cell phone number is valid.  A valid phone number
  * is a number with either 10 or 11 digits (as long as the first digit is a "1").
  * Valid phone numbers do not have 3 consecutive 5's in any part, nor do they
  * use punctuation where there should be numbers.
  *
  * @code
  *  dosomething_user_valid_cell('123-456-7890');
  *  # => true
  *  dosomething_user_valid_cell('123.456 7890');
  *  # => true
  *  dosomething_user_valid_cell('1 (123) 456-7890');
  *  # => true
  *  dosomething_user_valid_cell('123-555-9942');
  *  # => false
  *  dosomething_user_valid_cell('1 902 #@@ 1234');
  *  # => false
  * @endcode
  *
  * @param string $number
  *   The cell phone number that should be validated.
  * @return bool
  */
function dosomething_user_valid_cell($number) {
  preg_match('#^(?:\+?1([\-\s\.]{1})?)?\(?([0-9]{3})\)?(?:[\-\s\.]{1})?([0-9]{3})(?:[\-\s\.]{1})?([0-9]{4})#', $number, $valid);
  preg_match('#([0-9]{1})\1{9,}#', preg_replace('#[^0-9]+#', '', $number), $repeat);
  return !empty($valid) && empty($repeat) && strpos($number, '555') === FALSE;
}

