<?php
/**
 * @file
 * Code for the DoSomething Search feature.
 */

include_once 'dosomething_search.features.inc';

function dosomething_search_preprocess_page(&$vars) {
  $form = drupal_get_form('search_form');
  $vars['search_box'] = drupal_render($form);
}

function dosomething_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_form') {
    $form['#action'] = url('search/apachesolr_search');
    $form['#submit'] = array('dosomething_search_form_submit');
  }
}

function dosomething_search_preprocess_search_result(&$vars) {
}

function dosomething_search_preprocess_search_results(&$vars) {
}

/**
 * Process a search form submission.
 */
function dosomething_search_form_submit($form, &$form_state) {
  $keys = $form_state['values']['processed_keys'];
  if ($keys == '') {
    form_set_error('keys', t('Please enter some keywords.'));
    // Fall through to the form redirect.
  }

  $form_state['action'] = url('search/apachesolr_search');
  $form_state['redirect'] =  'search/apachesolr_search/' . $keys;
}