<?php
/**
 * @file
 * dosomething_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function dosomething_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Indoor',
    'description' => '',
    'format' => 'markdown',
    'weight' => 10,
    'uuid' => '006e4140-c312-48f8-9ec6-41e7589c4394',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sex',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0514e41f-82ca-4f5c-8ed8-acc3a83d7b39',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sporty',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => '067466eb-225d-49ed-baf1-33713b1ed50e',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '08f907cd-9cc0-4c00-bb8c-97c304599706',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Face to Face',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '3449ec13-932d-4951-81a7-8ab4eea05588',
    'vocabulary_machine_name' => 'action_type',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Environment',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '39b8003c-79fa-4397-9eae-2281607bf389',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Somber',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => '3b9731b6-6e98-4b2c-8525-78de118bf5f8',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Physical Health',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3db25e0b-7b89-468a-b2df-15952d902e6c',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Beneficiary',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '426a5ac5-2df4-4c1c-847e-bca28296c00f',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '6+ People',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '517ca696-0f39-4f18-99f1-6a4ce7616d32',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Homelessness',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '55ba62a6-208c-4e6d-a363-849c825ca27b',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Donate Something',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '64cc53a4-8386-498e-bb3a-2be3f3b88620',
    'vocabulary_machine_name' => 'action_type',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Improve a Space',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '64ef1251-586e-49f9-a612-e73b671c2b26',
    'vocabulary_machine_name' => 'action_type',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Make Something',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '6749c79e-70cb-42b6-aa4a-bd4aa670f1e2',
    'vocabulary_machine_name' => 'action_type',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Staff',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => '677a623c-5d95-40b2-a0b6-c8b41bbe28ac',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '1 Person',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '695bc629-f25f-42d1-864a-b843037282b9',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Start Something',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => '6a5833ac-29f6-43a2-b517-2bc917074f21',
    'vocabulary_machine_name' => 'action_type',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Host An Event',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '79ec246b-9909-4b40-a8f1-a1efbf59ca24',
    'vocabulary_machine_name' => 'action_type',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Disasters',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7d7b1db7-f7fb-43e2-ab72-4cfd4753aec1',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Bullying',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8b816991-8fbc-4edc-a056-0ddb507b5537',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Discrimination',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '963d87a3-3f9b-4af9-9d21-dc4d05e49ee2',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Outdoor',
    'description' => '',
    'format' => 'markdown',
    'weight' => 11,
    'uuid' => '998d75f6-fb2a-4484-8357-48eafe25a430',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Poverty',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a4b71323-a5e3-4993-82b1-7269b218392a',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Animals',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a78f6ca6-8528-499f-b4d7-a7470c652487',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Violence',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'aec30a55-5243-4266-b232-43095ff2ba1c',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '2-5 People',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => 'b3953a42-d176-48ec-be89-e2417c99d570',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Share Something',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => 'b750200f-b44e-410e-b0cd-5ddd22dd5c33',
    'vocabulary_machine_name' => 'action_type',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Silly',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => 'b75f5338-bd27-4746-b6c7-0177644d9796',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Volunteer',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => 'b762d221-89c2-4501-bd17-0ef7cdcb4a6d',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Happy',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => 'c317560a-10d2-4f7f-ac27-b9a0d9109f80',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Mental Health',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c3f6c4d6-98ea-4c07-bd8a-400ea3c4a285',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Take a Stand',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => 'db28f15c-be59-4438-a43f-cbbacf4a4a9a',
    'vocabulary_machine_name' => 'action_type',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'User Submitted',
    'description' => '',
    'format' => 'markdown',
    'weight' => 12,
    'uuid' => 'dfe9f578-cf88-46dc-ab97-24746f533516',
    'vocabulary_machine_name' => 'image_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Relationships',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e799eef7-5896-49ff-bba1-84866cfd81e2',
    'vocabulary_machine_name' => 'cause',
    'field_image_campaign_cover' => array(),
    'field_subtitle' => array(),
    'metatags' => array(),
  );
  return $terms;
}
