<?php
/**
 * @file
 * Code for the DoSomething Taxonomy feature.
 */

/**
 * Returns array of values of sponsor data.
 *
 * @param object $sponsor_field_wrapper
 *   An entity_metadata_wrapper object.
 *
 * @return mixed
 *   Multi-dimensional array of sponsor data or NULL if empty.
 *
 */
function dosomething_taxonomy_get_sponsors($sponsor_field_wrapper) {
  $sponsors = array();
  foreach ($sponsor_field_wrapper->getIterator() as $delta => $term_wrapper) {
    $sponsors[$delta]['name']  = $term_wrapper->name->value();
    if (property_exists($term_wrapper->field_image_sponsor_logo, 'nid')) {
      $sponsor_img_nid =  $term_wrapper->field_image_sponsor_logo->value()->nid;
      $sponsors[$delta]['img'] = dosomething_image_get_themed_image($sponsor_img_nid, 'sq', '310x310');
    }
  }
  if (!empty($sponsors)) {
    return $sponsors;
  }
  return NULL;
}

/**
 * Implements hook_taxonomy_term_view().
 */
function dosomething_taxonomy_taxonomy_term_view($term, $view_mode, $langcode) {
  // Don't grant access to term pages for non-staffers.
  if (!dosomething_user_is_staff()) {
    return drupal_access_denied();
  }
}
