<?php
/**
 * @file
 * Code for the dosomething_image feature.
 */

include_once 'dosomething_image.helpers.inc';
include_once 'dosomething_image.features.inc';

/**
 * Implements hook_node_form_alter().
 */
function dosomething_image_form_image_node_form_alter(&$form, &$form_state, $form_id) {
  // Do magic.
  drupal_add_js(drupal_get_path('module', 'dosomething_image') . '/dosomething_image_upload.js');

}

/**
 * Returns a themed image for any image field
 * @param int $nid
 *  The image node id.
 * @param string $ratio
 *  The image field to pull from the desired image ratio (portrait, landscape, square, thumb).
 * @param string $style
 *  The image style preset/size to return the image.
 * @param string $alt
 *  Optional - image alt text.
 * @param array $attributes
 *  Optional - key/value paired array of attributes to add to the image.
 *
 * @return string|null
 *  A themed image tag with no set height/width or null if no image path.
 */
function dosomething_image_get_themed_image($nid, $ratio, $style, $alt = '', $attributes = array()) {
  // Attempt to get that image from cache.
  if ($cached_img = cache_get('ds_img_' . $nid . '_' . $ratio . '_' . $style, 'cache_dosomething_image')) {
    return $cached_img->data;
  }
  // Theme the image.
  else {
    // Get the path of the themed image.
    $path = dosomething_image_get_themed_image_url($nid, $ratio, $style);

    if (!$path) {
      return NULL;
    }

    // Set drupal attributes.
    $attributes = drupal_attributes($attributes);

    // Construct themed image tag.
    $themed_image =  '<img src="' . check_url($path) . '" alt="' . check_plain($alt) . '"' .  $attributes .'>';

    // Store the themed image.
    cache_set('ds_img_' . $nid . '_' . $ratio . '_' . $style, $themed_image, 'cache_dosomething_image');

    return $themed_image;
  }
}

/**
 * Returns an image path for a given $nid and $ratio field.
 *
 * @param int $nid
 *  The image node id.
 *
 * @param string $ratio
 *  The image field to pull from the desired image ratio (portrait, landscape, square, thumb).
 *
 * @return
 *  An image url, or NULL if file doesn't exist.
 */
function dosomething_image_get_image_url($nid, $ratio) {
  $node = node_load($nid);
  $field_name = 'field_image_' . $ratio;
  if ($ratio == 'thumb') {
    $field_name = 'field_image_thumbnail';
  }
  if (!empty($node->{$field_name})) {
    return $node->{$field_name}[LANGUAGE_NONE][0]['uri'];
  }
  return NULL;
}

/**
 * Returns a sized image path.
 * @param int $nid
 *  The image node id.
 * @param string $ratio
 *  The image field to pull from the desired image ratio (vert, horiz, sq).
 * @param string $style
 *  The image dimensions (see Image Styles).
 *
 * @return string A sized image url.
 * A sized image url.
 */
function dosomething_image_get_themed_image_url($nid, $ratio, $style = NULL) {
  $base_path = dosomething_image_get_image_url($nid, $ratio);

  // If the image doesn't have the appropriate crop don't return a url.
  if (isset($base_path)) {
    // For videos
    if (!isset($style)) {
      return file_create_url($base_path);
    }
    return image_style_url($style, $base_path);
  }
}


/**
 * Returns a themed image for a given File $fid.
 *
 * @param int $fid
 *  The File fid.
 * @param string $style
 *  The image style preset/size to return the image.
 * @param string $alt
 *  Optional - image alt text.
 *
 * @return array
 *  A themed image tag with no set height/width.
 */
function dosomething_image_get_themed_image_by_fid($fid, $style, $alt = '') {
  $file = file_load($fid);
  if (!$file) {
    return NULL;
  }

  $image = image_load($file->uri);
  if (!$image) {
    $args = array(
      'path' => PARANEUE_PATH .'/images/no-image-found.png',
      'alt' => 'No image found placeholder',
      'title' => 'No Image Found',
      'attributes' => NULL,
    );
    return theme_image($args);
  }
  else {
    $content = array(
      'file' => array(
        '#theme' => 'image_style',
        '#style_name' => $style,
        '#path' => $image->source,
        '#alt' => $alt,
      ),
    );

    return drupal_render($content);
  }
}

/**
 * Returns a themed image URL for a given File $fid and $style preset.
 *
 * @param int $fid
 *  The File fid.
 * @param string $style
 *  The image style preset/size to return the image.
 *
 * @return string
 *  URL of the image source, or NULL if file doesn't exist.
 */
function dosomething_image_get_themed_image_url_by_fid($fid, $style) {
  $file = file_load($fid);
  if ($file) {
    return image_style_url($style, $file->uri);
  }
  return NULL;
}

/**
 * Implements hook_node_update().
 */
function dosomething_image_node_update($node) {
  if ($node->type == 'image') {
    /* @TODO: Eh, I'm not crazy about this, but it's a quick win for now.
     * We don't need to clear the whole cache, and should clear the cache
     * where this is referenced, but that can come later! */
    dosomething_image_cache_clear_all();
  }
}

/**
 * Clear cache on dosomething_image table.
 */
function dosomething_image_cache_clear_all() {
  cache_clear_all('*', 'cache_dosomething_image', TRUE);
}

/**
 * Implements hook_flush_caches().
 */
function dosomething_image_flush_caches() {
  return array('cache_dosomething_image');
}
