<?php
/**
 * @file
 * Installation and schema hooks for dosomething_campaign.module.
 */


/**
 * Deletes field_psa.
 */
function dosomething_campaign_update_7001(&$sandbox) {
  field_delete_field('field_psa');
}

/**
 * Sets new variable value.
 */
function dosomething_campaign_update_7002(&$sandbox) {
  $copy = "Join 250,000 people who have played since 2012!";
  variable_set('dosomething_campaign_sms_game_all_participants_copy', $copy);
}

/**
 * Sets Closed Callout variable.
 */
function dosomething_campaign_update_7003(&$sandbox) {
  $copy = "We'll hit you up when it re-opens";
  variable_set('dosomething_campaign_presignup_callout_copy', $copy);
}

/**
 * Sets lots more variables.
 */
function dosomething_campaign_update_7004(&$sandbox) {
  $value = "You did it!";
  variable_set('dosomething_campaign_confirmation_page_title', $value);
  $value = "Thanks for sharing!";
  variable_set('dosomething_campaign_sms_game_confirmation_page_title', $value);
  $value = "Find more campaigns";
  variable_set('dosomething_campaign_confirmation_page_button_text', $value);
  $value = "Find more campaigns";
  variable_set('dosomething_campaign_sms_game_confirmation_page_button_text', $value);
}
