<?php

/**
 * @file
 * Code for the dosomething_northstar module.
 */

include_once('dosomething_northstar.admin.inc');

// Config vars, if not set.
define('NORTHSTAR_URL', variable_get('dosomething_northstar_url', 'http://northstar.dev'));
define('NORTHSTAR_PORT', variable_get('dosomething_northstar_port', '8000'));
define('NORTHSTAR_VERSION', variable_get('dosomething_northstar_version', '1'));
define('NORTHSTAR_APP_ID', variable_get('dosomething_northstar_app_id', '456'));
define('NORTHSTAR_APP_KEY', variable_get('dosomething_northstar_app_key', 'abc4324'));

/**
 * Implements hook_menu().
 */
function dosomething_northstar_menu() {
  $items = array();
  $items['admin/config/services/northstar'] = array(
    'title' => 'Northstar',
    'description' => 'Manage Northstar connection settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_northstar_config_form'),
    'access arguments' => array('administer modules'),
    'file' => 'dosomething_northstar.admin.inc',
  );
  return $items;
}
/**
 * Implements hook_libraries_info().
 */
function dosomething_northstar_libraries_info() {
  $libraries['guzzle-php'] = array(
    'name' => 'Guzzle',
    'path' => 'lib',
    'files' => array(
      'php' => array(
        'autoload.php',
      ),
    ),
    'version' => 5.0,
  );
  return $libraries;
}

function dosomething_northstar_register_user($form_state) {
  global $user;
  // Build a user that Northstar expects.
  $ns_user = dosomething_northstar_build_ns_user($user, $form_state);

  // Send that to NS.


}

/**
 * Build a user json object, that's accepted by Northstar.
 *
 * @param obj $user
 *  Drupal user object
 *
 */
function dosomething_northstar_build_ns_user($user, $form_state) {
  return $ns_user = array(
    'email'         => $user->mail,
    'mobile'        => $user->field_mobile[LANGUAGE_NONE][0]['value'],
    'first_name'    => $user->field_first_name[LANGUAGE_NONE][0]['value'],
    'birthdate'     => $user->field_birthdate[LANGUAGE_NONE][0]['value'],
    'drupal_id'     => $user->uid,
    'password'      => $form_state['values']['pass'],
    // Address
    'country'       => $user->field_address[LANGUAGE_NONE][0]['country'],
    'addr_street1'  => $user->field_address[LANGUAGE_NONE][0]['thoroughfare'],
    'addr_street2'  => $user->field_address[LANGUAGE_NONE][0]['premise'],
    'addr_city'     => $user->field_address[LANGUAGE_NONE][0]['locality'],
    'addr_state'    => $user->field_address[LANGUAGE_NONE][0]['administrative_area'],
    'addr_zip'      => $user->field_address[LANGUAGE_NONE][0]['postal_code'],
  );
}

class Northstar {

  public $client;

  public function __construct()
  {
    $base_url = NORTHSTAR_URL;
    if (getenv('DS_ENVIRONMENT') === 'local') {
      $base_url .=  ":" NORTHSTAR_PORT;
    }
    $version = NORTHSTAR_VERSION;
    $client = new GuzzleHttp\Client([
      'base_url' => [$base_url . '/{version}/', ['version' => $version]],
      'defaults' => array(
        'headers' => [
          'X-DS-Application-Id' => NORTHSTAR_APP_ID,
          'X-DS-REST-API-Key' => NORTHSTAR_APP_KEY,
          'Content-Type' => 'application/json',
          'Accept' => 'application/json'
          ]
        ),
    ]);
    $this->client = $client;
  }

}
