#!/bin/bash

## Spin up the local environment and build the codebase.

yellow='\033[1;33m'
NC='\033[0m'

cd "$PROJECT_ROOT"

echo
echo -e "${yellow}Starting the containers...${NC}"
fin project start

${PROJECT_ROOT}/.docksal/commands/rebuild
fin exec ${PROJECT_ROOT}/.docksal/commands/db-import

echo
echo -e "${yellow}All done! Visit http://dosomething.docksal/${NC}"
