<?php
/**
 * @file
 * Code for the DoSomething Reportback feature.
 */

include_once 'dosomething_reportback.features.inc';

/**
 * Implements hook_entity_info().
 */
function dosomething_reportback_entity_info() {
  $info = array();
  $info['reportback'] = array(
    'label' => t('Reportback'),
    'base table' => 'dosomething_reportback',
    'entity keys' => array(
      'id' => 'rbid',
      'label' => 'rbid',
    ),
    'entity class' => 'ReportbackEntity',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'ReportbackEntityController',
    'module' => 'dosomething_reportback',
    'fieldable' => TRUE,
    'bundles' => array(
      'reportback' => array(
        'label' => t('Reportback'),
        'admin' => array(
          'path' => 'admin/reportback',
          'access arguments' => array('administer modules'),
        ),
      ),
    ),
    'views controller class' => 'EntityDefaultViewsController',
  );
  return $info;
}

/**
 * Implements hook_entity_property_info().
 */
function dosomething_reportback_entity_property_info() {
  $info = array();
  $properties = &$info['reportback']['properties'];
  $properties['rbid'] = array(
    'label' => t('Reportback rbid'),
    'description' => t('The unique ID of the reportback.'),
    'type' => 'integer',
    'schema field' => 'rbid',
    'entity views field' => TRUE,
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['nid'] = array(
    'label' => t('Node nid'),
    'description' => t('The node nid of the reportback.'),
    'type' => 'node',
    'schema field' => 'nid',
    'required' => TRUE,
    'entity views field' => TRUE,
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['uid'] = array(
    'label' => t('User uid'),
    'description' => t('The user uid of the reportback.'),
    'type' => 'user',
    'schema field' => 'uid',
    'required' => TRUE,
    'entity views field' => TRUE,
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['created'] = array(
    'label' => t('Created Date'),
    'description' => t('Date the reportback was created.'),
    'type' => 'date',
    'required' => TRUE,
    'schema field' => 'created',
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['updated'] = array(
    'label' => t('Last Updated'),
    'description' => t('Date the reportback was last updated.'),
    'type' => 'date',
    'required' => TRUE,
    'schema field' => 'updated',
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['quantity'] = array(
    'label' => t('Quantity'),
    'description' => t('The number of reportback_nouns reportback_verbed.'),
    'type' => 'integer',
    'required' => TRUE,
    'schema field' => 'quantity',
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['why_participated'] = array(
    'label' => t('Why Participated'),
    'description' => t('Why the user participated.'),
    'type' => 'text',
    'required' => TRUE,
    'schema field' => 'why_participated',
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['num_participants'] = array(
    'label' => t('Number of participants'),
    'description' => t('The number of reportback participants, if applicable.'),
    'type' => 'integer',
    'required' => FALSE,
    'schema field' => 'num_participants',
    'setter callback' => 'entity_property_verbatim_set',
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function dosomething_reportback_menu() {
  $items = array();
  $items['admin/reportback'] = array(
    'title' => 'Reportbacks',
    'description' => 'Configuration settings for Reportbacks.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer modules'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['reportback/%reportback'] = array(
    'title callback' => 'Reportback',
    'page callback' => 'dosomething_reportback_view_entity',
    'page arguments' => array(1),
    'access callback' => 'dosomething_reportback_access',
    'access arguments' => array('view', 1),
  );
  $items['reportback/%reportback/edit'] = array(
    'title callback' => 'Edit Reportback',
    'page callback' => 'dosomething_reportback_edit_entity',
    'page arguments' => array(1),
    'access callback' => 'dosomething_reportback_access',
    'access arguments' => array('edit', 1),
    'type' => MENU_LOCAL_TASK,
  );
  $items['reportback/%reportback/delete'] = array(
    'title callback' => 'Delete Reportback',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_reportback_delete_form', 1),
    'access callback' => 'dosomething_reportback_access',
    'access arguments' => array('delete', 1),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function dosomething_reportback_admin_paths() {
  $paths = array(
    'node/*/reportbacks' => TRUE,
  );
  return $paths;
}

/**
 * Access callback for reportback entity operations.
 */
function dosomething_reportback_access($op, $entity, $account = NULL) {
  global $user;
  if (!isset($account)) {
    $account = $user;
  }
  $perm_any = $op . ' any reportback';
  $perm_own = $op . ' own reportback';
  if (user_access($perm_any, $account)){
    return TRUE;
  }
  // Check that user has access to $op own, and is the author.
  return user_access($perm_own, $account) && $account->uid == $entity->uid;
}


/**
 * Implements hook_permission().
 */
function dosomething_reportback_permission() {
  return array(
    'delete any reportback' => array(
      'title' => t('Delete any reportback'),
    ),
    'delete own reportback' => array(
      'title' => t('Delete own reportback'),
    ),
    'edit any reportback' => array(
      'title' => t('Edit any reportback'),
    ),
    'edit own reportback' => array(
      'title' => t('Edit own reportback'),
    ),
    'view any reportback' => array(
      'title' => t('View any reportback'),
    ),
    'view own reportback' => array(
      'title' => t('View own reportback'),
    ),
  );
}

/**
 * Menu autoloader for /reportback.
 */
function reportback_load($id) {
  $reportback = entity_load('reportback', array($id));
  return array_pop($reportback);
}

/**
 * Callback for /reportback/ID page.
 */
function dosomething_reportback_view_entity($entity) {
  return entity_view('reportback', array($entity->rbid => $entity), 'full');
}

/**
 * Process variables for entity.tpl.php.
 *
 * @see template_preprocess_entity in Entity API module.
 */
function dosomething_reportback_preprocess_entity(&$variables) {
  if ($variables['elements']['#entity_type'] == 'reportback' && $variables['view_mode'] == 'full') {
    // Enables reportback.tpl.php naming suggestion.
    $variables['theme_hook_suggestions'][] = 'reportback';
    $entity = $variables['elements']['#entity'];
    if (dosomething_reportback_access('edit', $entity)) {
      $variables['edit_link'] = l('Update', 'reportback/' . $entity->rbid . '/edit');
    }
    if (dosomething_reportback_access('delete', $entity)) {
      $variables['delete_link'] = l('Delete', 'reportback/' . $entity->rbid . '/delete');
    }
  }
}

/**
 * Callback for /reportback/ID/edit page.
 */
function dosomething_reportback_edit_entity($entity) {
  // We need the node to pass through to rb form for quantity values.
  $node = node_load($entity->nid);
  $wrapper = entity_metadata_wrapper('node', $node);
  return drupal_get_form('dosomething_reportback_form', $wrapper, $entity);
}

/**
 * Form constructor for a node reportback create/update form.
 *
 * @param object $wrapper
 *   An entity_metadata_wrapper of the node to report back for.
 *
 * @ingroup forms
 */
function dosomething_reportback_form($form, &$form_state, $wrapper, $entity = NULL) {
  // If entity is not set, this is a create form.
  if (!isset($entity)) {
    $entity = entity_create('reportback', array(
      'rbid' => 0,
      'quantity' => '',
      'why_participated' => NULL,
    ));
    $submit_label = t("Submit");
  }
  // Else, it's update form.  Display updated date.
  else {
    $form['header'] = array(
      '#markup' => '<p class="legal">Last updated ' . format_date($entity->updated, 'short') . '</p>',
    );
    $submit_label = t("Update");
  }
  $form['rbid'] = array(
    '#type' => 'hidden',
    '#default_value' => $entity->rbid,
  );
  $form['nid'] = array(
    '#type' => 'hidden',
    '#default_value' => $wrapper->nid->value(),
  );
  $form['why_participated'] = array(
    '#type' => 'textarea',
    '#required' => TRUE,
    '#title' => t('Why is this campaign important to you?'),
    '#default_value' => $entity->why_participated,    
  );
  $form['quantity'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t("Total number of @noun @verb", array(
        '@noun' => $wrapper->field_reportback_noun->value(),
        '@verb' => $wrapper->field_reportback_verb->value(),
      )
    ),
    '#default_value' => $entity->quantity,
  );
  // @todo: Add conditional around this if display_num_participants.
  $form['num_participants'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Number of participants'),
    '#default_value' => $entity->num_participants,    
  );

  // Attach all reportback entity fields to the form:
  field_attach_form('reportback', $entity, $form, $form_state);
  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => $submit_label,
    ),
  );
  return $form;
}

/**
 * Submit callback for dosomething_reportback_form().
 */
function dosomething_reportback_form_submit($form, &$form_state) {
  global $user;
  // @todo: Check that $form_state['values']['nid'] == arg(1), 
  // If we can assume this form is always rendered on campaign.
  $values = $form_state['values'];
  $values['uid'] = $user->uid;
  $values['files'] = array();
  // Loop through User Reportback Images field:
  foreach ($values['field_image_user_reportback'][LANGUAGE_NONE] as $delta => $file) {
    // Exclude the "add another" field (which has fid value 0).
    if ($file['fid'] != 0) {
      $values['files'][] = $file;
    }
  }
  // @todo: Sort $files array by the weight field, to allow for re-ordering.
  if ($values['rbid'] == 0) {
    $entity = entity_create('reportback', array());
    $rbid = dosomething_reportback_insert_reportback($values);
    if ($rbid) {
      // Load node to get reportback message confirmation.
      $node_wrapper = entity_metadata_wrapper('node', $values['nid']);
      drupal_set_message($node_wrapper->field_reportback_confirm_msg->value());
      return;
    }
  }
  else {
    $rbid = dosomething_reportback_update_reportback($values['rbid'], $values);
    if ($rbid) {
      drupal_set_message(t("Your submission has been updated."));
      return;
    }
  }
  // If we didn't break out of function by now, insert/update didn't work.
  drupal_set_message(t("An error has occurred."), 'error');
}

/**
 * Form constructor for a reportback delete form.
 *
 * @param object $entity
 *   The reportback entity to delete.
 *
 * @ingroup forms
 */
function dosomething_reportback_delete_form($form, &$form_state, $entity) {
  $form['rbid'] = array(
    '#type' => 'hidden',
    '#default_value' => $entity->rbid,
  );
  $form['nid'] = array(
    '#type' => 'hidden',
    '#default_value' => $entity->nid,
  );
  $form['warning'] = array(
    '#markup' => t("Are you sure you want to delete this reportback?  This cannot be undone."),
  );
  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Delete'),
    ),
  );
  return $form;
}

/**
 * Submit callback for dosomething_reportback_delete_form().
 */
function dosomething_reportback_delete_form_submit($form, &$form_state) {
  $rbid = $form_state['values']['rbid'];
  // Check for user screwing with form values via browser type firebuggin' things.
  // This check will only work if the form lives only on reportback/*/delete.
  if ($rbid == arg(1)) {
    dosomething_reportback_delete_reportback($rbid);
    // Redirect back to the node that the reportback was for.
    $form_state['redirect'] = 'node/' . $form_state['values']['nid'];
    drupal_set_message(t("Reportback deleted."));
  }
  // Else, there was some rat fuckery.
  drupal_set_message(t("There was an error processing your request."));
}

/**
 * Inserts a reportback entity.
 *
 * @param array $values
 *   An array of expected reportback values.
 *
 * @return mixed
 *   Newly inserted reportback rbid if success, or FALSE if error.
 */
function dosomething_reportback_insert_reportback($values) {
  $entity = entity_create('reportback', array());
  return dosomething_reportback_save($entity, $values);
}

/**
 * Updates a reportback entity.
 *
 * @param array $values
 *   An array of expected reportback values.
 *
 * @return mixed
 *   The updated reportback rbid if success, or FALSE if error.
 */
function dosomething_reportback_update_reportback($rbid, $values) {
  $entity = entity_load_single('reportback', $rbid);
  return dosomething_reportback_save($entity, $values);
}

/**
 * Deletes a reportback entity.
 *
 * @param int $rbid
 *   Reportback rbid to delete.
 *
 * @return
 *   FALSE, if error.
 */
function dosomething_reportback_delete_reportback($rbid) {
  return entity_delete('reportback', $rbid);
}

/**
 * Checks if a reportback exists for given $nid and $uid.
 *
 * @param int $nid
 *   The node nid of the reportback to check.
 * @param int $uid
 *   Optional - the user uid of reportback to check.  
 *   If not given, uses global $user->uid.
 *
 * @return mixed
 *   The rbid of reportback or FALSE if it doesn't exist.
 */
function dosomething_reportback_exists($nid, $uid = NULL) {
  if ($uid == NULL) {
    global $user;
    $uid = $user->uid;
  }
  $result = db_select('dosomething_reportback', 'r')
    ->condition('uid', $uid)
    ->condition('nid', $nid)
    ->fields('r', array('rbid'))
    ->execute();
  $rbid = $result->fetchField(0);
  // If a rbid was found, return it.
  if (is_numeric($rbid)) {
    return $rbid;
  }
  // Otherwise return FALSE.
  return FALSE;
}

/**
 * Saves a reportback entity with given values.
 *
 * @param object $entity
 *   The reportback entity to save (may be a blank entity if insert).
 * @param array $values
 *   The reportback entity values to save.
 *
 * @return mixed
 *   The reportback entity rbid if success, or FALSE if error.
 */
function dosomething_reportback_save($entity, $values) {
  try {
    // Load metadata wrapper for easier set methods.
    $wrapper = entity_metadata_wrapper('reportback', $entity);
    // Set entity properties.
    dosomething_reportback_set_properties(&$wrapper, $values);
    // Set entity files.
    dosomething_reportback_set_files(&$wrapper, $values);
    // Save the entity.
    $wrapper->save();
    // Return reportback rbid.
    return $wrapper->rbid->value();
  }
  catch (Exception $e) {
    watchdog('dosomething_reportback', $e, array(), WATCHDOG_ERROR);
    return FALSE;
  }
}

/**
 * Sets a reportback entity's properties via entity metadata wrapper.
 *
 * @param object $wrapper
 *   The reportback entity wrapper to set properties for.
 * @param array $values
 *   Array of property values to set, indexed by the property name.
 */
function dosomething_reportback_set_properties(&$wrapper, $values) {
  // List all possible entity properties to write.
  $properties = array('uid', 'nid', 'quantity', 'why_participated', 'num_participants');
  // For each of them:
  foreach ($properties as $property) {
    // If we have a value set for this property.
    if (isset($values[$property])) {
      // Set property value in wrapper.
      $wrapper->{$property}->set($values[$property]);
    }
  }
}

/**
 * Sets a reportback entity's files via entity metadata wrapper.
 *
 * @param object $wrapper
 *   The reportback entity wrapper to set properties for.
 * @param array $values
 *   Multi-dimensional array of files to set.
 */
function dosomething_reportback_set_files(&$wrapper, $values) {
  // Get total count of images present on entity.
  $num_images = count($wrapper->field_image_user_reportback);
  $i = 0;
  // Loop through all files provided in $values.
  foreach ($values['files'] as $delta => $file) {
    $wrapper->field_image_user_reportback[$i] = array('fid' => (int) $file['fid']);
    $i++;
  }
  // Are there existing images in entity field not present in $values['files']?
  if (isset($wrapper->field_image_user_reportback[$i])) {
    // Loop through remaining image values in the entity field.
    for ($i=$i; $i<$num_images; $i++) {
      // It means they were removed, so unset them.
      unset($wrapper->field_image_user_reportback[$i]);
    }
  }
}
