<?php
/**
 * @file
 * Code for the dosomething_gladiatior.module.
 */

include_once('dosomething_gladiator.admin.inc');

define('GLADIATOR_URL', variable_get('dosomething_gladiator_url', 'http://homestead.app/api'));
define('GLADIATOR_VERSION', variable_get('dosomething_gladiator_version', 'v1'));

function dosomething_gladiator_init() {
  $client = _dosomething_gladiator_build_http_client();

  $options = [
    'method' => 'GET',
    'headers' => $client['headers'],
  ];

  $response = drupal_http_request($client['base_url'] . '/contests', $options);
  $contests = json_decode($response->data)->data;

  foreach ($contests as $contestData) {
    // $contest = json_decode($contestData->data);

    // dosomething_helpers_set_variable('node', $contest->campaign->id, 'signup_data_form_status', TRUE);
    dosomething_helpers_set_variable('node', 1485, 'signup_data_form_competition_signup', TRUE);
  }
}

function dosomething_gladiator_menu() {
  $items = [];
  $items['admin/config/services/gladiator'] = array(
    'title' => 'Gladiator',
    'description' => 'Manage Gladiator connection settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_gladiator_config_form'),
    'access arguments' => array('administer modules'),
    'file' => 'dosomething_gladiator.admin.inc',
  );
  return $items;
}
/**
 * Build the Guzzle HTTP Client to make requests to Gladiator.
 *
 * https://github.com/DoSomething/gladiator
 */
function _dosomething_gladiator_build_http_client() {
  $client = [
    'base_url' => GLADIATOR_URL . '/' . GLADIATOR_VERSION,
    'headers' => ['Content-Type' => 'application/json', 'Accept' => 'application/json'],
  ];
  return $client;

}

/**
 * Sends a user to Gladiator (https://github.com/DoSomething/gladiator)
 *
 * @param object $user
 *   The user that signup up for the competition.
 * @param array $values
 *   Values from the signup data form.
 */
function dosomething_gladiator_send_user_to_gladiator($user, $values) {
  $client = _dosomething_gladiator_build_http_client();

  $options = [
  'method' => 'POST',
  'headers' => $client['headers'],
  'data' =>
      json_encode([
        'id' => $user->mail,
        'term' => 'email',
        'campaign_id' => $values['nid'],
        'campaign_run_id' => $values['run_nid'],
      ]),
  ];

  $response = drupal_http_request($client['base_url'] . '/users', $options);

  if ($response->code == 200 && module_exists('stathat')) {
    stathat_send_ez_count('drupal - Gladiator - user sent - count', 1);
  }
  else {
    // Log as a watchdog error, and stathat value.
    if (module_exists('stathat')) {
     stathat_send_ez_count('drupal - Gladiator - user failed - count', 1);
    }
    // Save fail to a db log so we can easily export.
    db_insert('dosomething_gladiator_failed_task_log')
      ->fields(array(
        'uid' => $user->uid,
        'mail' => $user->mail,
        'nid' => $values['nid'],
        'run_nid' => $values['run_nid'],
        'timestamp' => REQUEST_TIME,
        'response_code' => $response->code,
        'response_values' => json_encode($response),
        ))
      ->execute();

    watchdog('dosomething_gladiator','user not migrated', array('user' => $user->mail), WATCHDOG_ERROR);
  }

}
