<?php

/**
 * @file
 * Array of endpoints ("keywords") and the name of the workflows they are each
 * associated with.
 */
$keywords['start-campaign-transition'] = 'dosomething_sms_start_campaign_transition';
$keywords['sms-game-paths'] = 'dosomething_sms_game_paths';
$keywords['comeback-clothes-reportback'] = 'dosomething_sms_comeback_clothes_reportback';
$keywords['thumbwars-reportback'] = 'dosomething_sms_thumbwars_reportback';
$keywords['imaboss-reportback'] = 'dosomething_sms_imaboss_reportback';
$keywords['bithdaymail-reportback'] = 'dosomething_sms_birthdaymail_reportback';
