<?php

/**
 * @file
 * Array of endpoints ("keywords") and the name of the workflows they are each
 * associated with. Keyword/workflow pairs here are for SMS games.
 */
$keywords['preg-text-responder'] = 'sms_flow_preg_text_responder';
$keywords['mcommons-ordered-paths'] = 'sms_flow_mcommons_ordered_paths';
$keywords['mcommons-random-path'] = 'sms_flow_mcommons_random_path';
$keywords['mcommons-timed-paths'] = 'sms_flow_mcommons_timed_paths';
