<?php
/**
 * @file
 * Code for the dosomething_campaign_run feature.
 */

include_once 'dosomething_campaign_run.features.inc';

/**
 * Adds loaded closed campaign_run node to the given parent campaign's $vars.
 *
 * @see dosomething_campaign_preprocess_node().
 */
function dosomething_campaign_run_preprocess_closed(&$vars) {
  if (!isset($vars['nid'])) { return; }

  // If a closed Campaign Run node exists:
  if ($closed_run_nid = dosomething_campaign_run_get_closed_run_nid($vars['nid'])) {
    // Load the closed campaign_run.
    $wrapper = entity_metadata_wrapper('node', $closed_run_nid);
    // Gather the campaign_run vars.
    dosomething_campaign_run_preprocess_text_vars($vars, $wrapper);
    dosomething_campaign_run_preprocess_winners($vars, $closed_run_nid);
  }
}

/**
 * Adds given campaign_run entity $wrapper values to $vars.
 *
 * @param array $vars
 *   Array of variables via hook_preprocess_node.
 * @param object $wrapper
 *   Entity metadata wrapper of the campaign_run node to gather values from.
 */
function dosomething_campaign_run_preprocess_text_vars(&$vars, $wrapper) {
  $text_fields = array(
    'additional_text',
    'additional_text_title',
    'intro',
    'total_participants',
    'total_quantity',
    'total_quantity_label',
  );
  foreach ($text_fields as $key => $label) {
    $field = "field_{$label}";
    $vars[$label] = $wrapper->{$field}->value();
  }
}

/**
 * Adds the $winners array to the campaign node.
 *
 * @param array $vars
 *   Array of variables via hook_preprocess_node.
 * @param int $nid
 *   Node id of the campaign run node.
 */
function dosomething_campaign_run_preprocess_winners(&$vars, $nid) {
  $closed_node = node_load($nid);
  // Get all winners
  $winner_count =  count($closed_node->field_winners[LANGUAGE_NONE]);
  $winners = array();
  $text_fields = array(
    'field_winner_type',
    'field_winner_quote',
    'field_winner_description',
  );
  for ($i = 0; $i < $winner_count; $i++) {
    $winner =  entity_load('field_collection_item', array($closed_node->field_winners[LANGUAGE_NONE][$i]['value']));
    $entity_id = $closed_node->field_winners[LANGUAGE_NONE][$i]['value'];
    $winners[$i]['uid'] = $winner[$entity_id]->field_user[LANGUAGE_NONE][0]['target_id'];
    $winners[$i]['fname'] = user_load($winners[$i]['uid'])->field_first_name[LANGUAGE_NONE][0]['value'];
    foreach($text_fields as $text_field) {
      $winners[$i][$text_field] = $winner[$entity_id]->{$text_field}[LANGUAGE_NONE][0]['value'];
    }
  }
  $vars['winners'] = $winners;

}

/**
 * For given campaign $nid, return its closed Campaign Run nid.
 *
 * For now, this just returns a campaign_run node that references the $nid.
 * As we build out multiple runs per campaign, we'll need to add logic
 * to determine sequence.
 *
 * @param int $nid
 *   A campaign node nid.
 *
 * @return mixed
 *   Returns the closed campaign_run node $nid if exists, FALSE if not.
 */
function dosomething_campaign_run_get_closed_run_nid($nid) {
   // Query field_data_field_campaigns for campaign_run node referencing $nid.
   $result = db_select('field_data_field_campaigns', 'c')
    ->fields('c', array('entity_id'))
    ->condition('field_campaigns_target_id', $nid)
    ->condition('bundle', 'campaign_run')
    ->execute();
  return $result->fetchField(0);
}
