<?php

/**
 * @file
 * Class of constants to be used for sms_flow_game game_id's.
 *
 * Constants shouldn't be removed from this and repurposed for other SMS flows
 * unless you know what you're getting yourself into.
 */
class SmsFlowGameConstants {
  const WYR_GAME                = 2;
  const FINANCIAL_ED_TIPS       = 3;
  const PBJ_MARKETING_TIPS      = 4;
  const PBJ_DRIVE_TIPS          = 5;
  const PREGTEXT_WAIT_TIPS      = 6;
  const PREGTEXT_SAFE_TIPS      = 7;
  const PREGTEXT_PARENT_TIPS    = 8;
  const PREGTEXT_RIGHTS_TIPS    = 9;
  const THUMBWARS_IDEAS_TIPS    = 10;
  const THUMBWARS_FACTS_TIPS    = 11;
  const PUPPYTEXT_FAQ_TIPS      = 12;
  const PUPPYTEXT_DOG_TIPS      = 13;
  const OK_ART_TIPS             = 14;
  const CLIMATE_SAS_NINJA       = 15;
  const IHEARTDAD_BP_TIPS       = 16;
  const IHEARTDAD_HEALTH_TIPS   = 17;
  const IHEARTDAD_GUIDE         = 18;
  const HUNT_INSPIRE            = 19;
  const BDAYMAIL_TIPS           = 20;
  const GIVEASPIT_ORDERED_TIPS  = 21;
  const GIVEASPIT_RANDOM_TIPS   = 22;
  const SURVIVORS_RANDOM_TIPS   = 23;
  const FEDUP_RANDOM_TIPS       = 24;
  const MARKT_50CANS_TIPS       = 25;
  const RUN_50CANS_TIPS         = 26;
  const STATS_50CANS_TIPS       = 27;
  const GGW_EMAIL_TIPS          = 28;
  const GGW_COMP_TIPS           = 29;
  const GGW_PHONE_TIPS          = 30;
  const GGW_FBOOK_TIPS          = 31;
  const GGW_TWEET_TIPS          = 32;
  const GGW_VIDCHAT_TIPS        = 33;
  const GGW_INSTA_TIPS          = 34;
  const GGW_TABLET_TIPS         = 35;
  const TFJ_MARKET_TIPS         = 36;
  const TFJ_RUN_TIPS            = 37;
  const TFJ_PRIZE_GUIDE         = 38;
}
