<?php
/**
 * @file
 * Module file for DoSomething Kudos functionality.
 */

include_once 'includes/Kudos.php';
include_once 'includes/KudosController.php';
include_once 'includes/KudosTransformer.php';


/**
 * @return array
 */
function dosomething_kudos_entity_info() {
  $info = [];
  $info['kudos'] = [
    'label' => t('Kudos'),
    'base table' => 'dosomething_kudos',
    'entity keys' => [
      'id' => 'kid',
      'label' => 'kid',
    ],
    'entity class' => 'Kudos',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'KudosController',
    'module' => 'dosomething_kudos',
  ];

  return $info;
}


/**
 * @param $params
 *
 * @return EntityFieldQuery
 */
function dosomething_kudos_build_kudos_query($params) {
  // @TODO: implement use of $params for custom queries.
  // @see dosomething_campaign_get_campaigns_query() as an example.

  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'kudos');

  return $query;
}


/**
 * @param array $params
 * @param null $count
 * @param int $start
 *
 * @return array
 */
function dosomething_kudos_get_kudos_query($params = [], $count = NULL, $start = 0) {
  $query = dosomething_kudos_build_kudos_query($params);

  if ($count && is_int($count)) {
    $query->range($start, $count);
  }

  $result = $query->execute();
  return array_keys($result['kudos']);
}
