<?php
/**
 * @file
 * Module file for DoSomething Kudos functionality.
 */

include_once 'dosomething_kudos.kudos.inc';


/**
 * Create a Kudos record.
 *
 * @param $values array Associated array of database column name and value pairs.
 * @return DatabaseStatementInterface|int
 * @throws Exception
 */
function dosomething_kudos_create($values) {
  return db_insert('dosomething_kudos')->fields($values)->execute();
}


/**
 * Delete a specified Kudos record.
 *
 * @param $kid
 * @return DatabaseStatementInterface
 */
function dosomething_kudos_destroy($kid) {
  return db_delete('dosomething_kudos')->condition('kid', $kid)->execute();
}
