<?php
/**
 * @file
 * Module file for DoSomething Kudos functionality.
 */

module_load_include('php', 'dosomething_api', 'includes/ApiCache');

include_once 'includes/Kudos.php';
include_once 'includes/KudosController.php';
include_once 'includes/KudosTransformer.php';


/**
 * Implements hook_entity_info().
 *
 * @return array
 */
function dosomething_kudos_entity_info() {
  $info = [];

  $info['kudos'] = [
    'label' => t('Kudos'),
    'base table' => 'dosomething_kudos',
    'entity keys' => [
      'id' => 'kid',
      'label' => 'kid',
    ],
    'entity class' => 'Kudos',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'KudosController',
    'module' => 'dosomething_kudos',
  ];

  return $info;
}


/**
 * Build out query to collect Kudos based on supplied filter parameters.
 *
 * @param array $params An associative array of conditions to filter by:
 *  - fid: (string|array) Single string or array of multiple Reportback Item ids.
 * @return EntityFieldQuery
 */
function dosomething_kudos_build_kudos_query($params) {
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'kudos');

  if (isset($params['fid'])) {
    if (is_array($params['fid'])) {
      $query->propertyCondition('fid', $params['fid'], 'IN');
    } else {
      $query->propertyCondition('fid', $params['fid'], '=');
    }
  }

  return $query;
}


/**
 * Execute query to collect Kudos based on supplied filter parameters.
 *
 * @param array $params An associative array of conditions to filter by:
 *  - fid: (string|array) Single string or array of multiple Reportback Item ids.
 *  - count: (int) Number of Kudos items to return; will default to NULL.
 *  - start: (int) Which Kudos to start with in collection; predominantly used for pagination.
 * @return array
 */
function dosomething_kudos_get_kudos_query($params = []) {
  $count = isset($params['count']) ? $params['count'] : NULL;
  $start = isset($params['start']) ? $params['start'] : 0;

  $query = dosomething_kudos_build_kudos_query($params);

  if ($count && is_int($count) & $count !== 'all') {
    $query->range($start, $count);
  }

  $result = $query->execute();
  return array_keys($result['kudos']);
}


/**
 * Sort kudos collection based on taxonomy term and then group them by term.
 *
 * @param array $data Collection of individual kudos items.
 * @param string $display
 * @return array
 */
function dosomething_kudos_sort($data, $display = 'teaser') {
  // The array containing collection of kudos items passed to this function
  // consists of individual kudos items. However, within this collection
  // there could be multiple kudos items that all fall within the same
  // taxonomy term. So the following series of functions sort and then
  // group the kudos based on taxonomy term, along with providing a total
  // count of kudos for each term.

  usort($data, 'dosomething_kudos_sort_by_taxonomy_term');

  $data = dosomething_kudos_group_by_taxonomy_term($data, $display);
  $data = dosomething_kudos_get_totals_by_taxonomy_term($data);
  return $data;
}


/**
 * Sort kudos collection by taxonomy term id using a value comparison function.
 *
 * @param array|object $a Array of Kudos data or instance of Kudos class object.
 * @param array|object $b Array of Kudos data or instance of Kudos class object.
 * @return mixed
 */
function dosomething_kudos_sort_by_taxonomy_term($a, $b) {
  $a = (object) $a;
  $b = (object) $b;

  // Sort by taxonomy term id.
  $result = $a->term['id'] - $b->term['id'];

  // If term ids are identical, sort by kudos id.
  if (!$result) $result = $a->id - $b->id;

  return $result;
}


/**
 * Group all kudos in collection and organize them by taxonomy term.
 *
 * @param array $data Array containing Kudos items.
 * @return array
 */
function dosomething_kudos_group_by_taxonomy_term($data, $display = 'teaser') {
  $terms = [];

  foreach ($data as $item) {
    if (!($item instanceof Kudos)) {
      $item = (object) $item;
    }

    if (!array_key_exists($item->term['id'], $terms)) {
      $terms[$item->term['id']] = [
        'term' => $item->term,
      ];
    }

    $output = [
      'id' => $item->id,
      'user' => $item->user,
    ];

    if ($display === 'full') {
      $output['reportback_item'] = $item->reportback_item;
    }

    if (isset($item->uri)) {
      $output['uri'] = $item->uri;
    }

    $terms[$item->term['id']]['kudos_items']['data'][] = $output;
  }


  return array_values($terms);
}


/**
 * Calculate total kudos per taxonomy term for a collection of kudos.
 *
 * @param array $data
 * @return array
 */
function dosomething_kudos_get_totals_by_taxonomy_term($data) {
  $output = [];

  foreach ($data as $term) {
    $total = count($term['kudos_items']['data']);

    $term['kudos_items'] = ['total' => $total] + ['data' => $term['kudos_items']['data']];

    $output[] = $term;
  }

  return $output;
}

/**
 * Given a term in the kudos vocab, return the tid of that term.
 * @param  $name string
 * @return int
 */
function dosomething_kudos_get_term_id_by_name($name) {
  $term = taxonomy_get_term_by_name($name, 'kudos');

  return array_pop($term)->tid;
}

/**
 * Aggregate the total number of Kudos kudoed on a particular file.
 * @param  string $fid
 * @param  string $term
 * @return int
 */
function dosomething_kudos_get_total_for_file_by_term_name($fid, $term) {
  $tid = dosomething_kudos_get_term_id_by_name($term);
  $kudos = db_select('dosomething_kudos', 'k')
      ->fields('k')
      ->condition('fid', $fid, '=')
      ->condition('tid', $tid, '=')
      ->execute()
      ->rowCount();
  return $kudos;
}

/**
 * Get the ids of Kudos on a file by a user and pair with corresponding term
 * @param  string $fid
 * @return array
 */
function dosomething_kudos_get_kudos_for_user_by_file($fid) {
  global $user;

  $kudos = db_select('dosomething_kudos', 'k')
      ->fields('k', ['tid', 'kid'])
      ->condition('fid', $fid, '=')
      ->condition('uid', $user->uid, '=')
      ->execute()
      ->fetchAllAssoc('tid');

  return $kudos;
}

/**
 * Check to see if the kudos term has been selected by the user on specified
 * reportback.
 *
 * @param  string $id
 * @param  object $reportback_item
 * @return bool
 */
function dosomething_kudos_term_is_selected($id, $reportback_item) {
  if (! $reportback_item->existing_kids) {
    return false;
  }

  if (! isset($reportback_item->existing_kids[$id])) {
    return false;
  }

  return true;
}

/**
 * Get the icon associated with the kudos term id.
 *
 * @param  string $id
 * @return string
 * @TODO: this will eventually be changed to refere to SVG icon paths for our custom kudos icons!
 */
function dosomething_kudos_get_icon_by_term_id($id) {
  $id = (string) $id;

  $icons = [
    '641' => '&#128150;',
    '646' => '&#128169;',
  ];

  return $icons[$id];
}

/**
 * Get the count for a kudos term on a Reportback item by the
 * kudos term id.
 *
 * @param  string $id
 * @param  object $reportbackItem
 * @return string
 */
function dosomething_kudos_get_count_by_term_id($id, $reportbackItem) {
  $id = (string) $id;

  $count_term = [
    '641' => 'likes',
    '646' => 'poos',
  ];

  return $reportbackItem->$count_term[$id];
}


